package fr.afcepf.ai83.itinelib.model;

// Generated 29 juin 2012 16:59:41 by Hibernate Tools 3.4.0.Beta1

import java.util.Date;
import java.util.HashSet;
import java.util.Set;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.GeneratedValue;
import static javax.persistence.GenerationType.IDENTITY;
import javax.persistence.Id;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.OneToMany;
import javax.persistence.Table;
import javax.persistence.Temporal;
import javax.persistence.TemporalType;

/**
 * Abonnement generated by hbm2java
 */
@Entity
@Table(name = "abonnement", catalog = "itinelib")
public class Abonnement implements java.io.Serializable {

	private Integer idabonnement;
	private Typeabonnement typeabonnement;
	private Abonne abonne;
	private Date dhsouscription;
	private Date dhresiliation;
	private Set<Resaglobale> resaglobales = new HashSet<Resaglobale>(0);
	private Set<Registre> registres = new HashSet<Registre>(0);
	private Set<Historiqueabonnement> historiqueabonnements = new HashSet<Historiqueabonnement>(
			0);

	public Abonnement() {
	}

	public Abonnement(Typeabonnement typeabonnement, Abonne abonne,
			Date dhsouscription) {
		this.typeabonnement = typeabonnement;
		this.abonne = abonne;
		this.dhsouscription = dhsouscription;
	}

	public Abonnement(Typeabonnement typeabonnement, Abonne abonne,
			Date dhsouscription, Date dhresiliation,
			Set<Resaglobale> resaglobales, Set<Registre> registres,
			Set<Historiqueabonnement> historiqueabonnements) {
		this.typeabonnement = typeabonnement;
		this.abonne = abonne;
		this.dhsouscription = dhsouscription;
		this.dhresiliation = dhresiliation;
		this.resaglobales = resaglobales;
		this.registres = registres;
		this.historiqueabonnements = historiqueabonnements;
	}

	@Id
	@GeneratedValue(strategy = IDENTITY)
	@Column(name = "IDABONNEMENT", unique = true, nullable = false)
	public Integer getIdabonnement() {
		return this.idabonnement;
	}

	public void setIdabonnement(Integer idabonnement) {
		this.idabonnement = idabonnement;
	}

	@ManyToOne(fetch = FetchType.EAGER)
	@JoinColumn(name = "IDTYPE", nullable = false)
	public Typeabonnement getTypeabonnement() {
		return this.typeabonnement;
	}

	public void setTypeabonnement(Typeabonnement typeabonnement) {
		this.typeabonnement = typeabonnement;
	}

	@ManyToOne()
	@JoinColumn(name = "IDABONNE", nullable = false)
	public Abonne getAbonne() {
		return this.abonne;
	}

	public void setAbonne(Abonne abonne) {
		this.abonne = abonne;
	}

	@Temporal(TemporalType.TIMESTAMP)
	@Column(name = "DHSOUSCRIPTION", nullable = false, length = 19)
	public Date getDhsouscription() {
		return this.dhsouscription;
	}

	public void setDhsouscription(Date dhsouscription) {
		this.dhsouscription = dhsouscription;
	}

	@Temporal(TemporalType.TIMESTAMP)
	@Column(name = "DHRESILIATION", length = 19)
	public Date getDhresiliation() {
		return this.dhresiliation;
	}

	public void setDhresiliation(Date dhresiliation) {
		this.dhresiliation = dhresiliation;
	}

	@OneToMany( mappedBy = "abonnement")
	public Set<Resaglobale> getResaglobales() {
		return this.resaglobales;
	}

	public void setResaglobales(Set<Resaglobale> resaglobales) {
		this.resaglobales = resaglobales;
	}

	@OneToMany(mappedBy = "abonnement")
	public Set<Registre> getRegistres() {
		return this.registres;
	}

	public void setRegistres(Set<Registre> registres) {
		this.registres = registres;
	}

	@OneToMany(mappedBy = "abonnement")
	public Set<Historiqueabonnement> getHistoriqueabonnements() {
		return this.historiqueabonnements;
	}

	public void setHistoriqueabonnements(
			Set<Historiqueabonnement> historiqueabonnements) {
		this.historiqueabonnements = historiqueabonnements;
	}

}
