package fr.afcepf.ai83.itinelib.model;

// Generated 29 juin 2012 16:59:41 by Hibernate Tools 3.4.0.Beta1

import java.util.Date;
import java.util.HashSet;
import java.util.Set;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.GeneratedValue;
import static javax.persistence.GenerationType.IDENTITY;
import javax.persistence.Id;
import javax.persistence.JoinColumn;
import javax.persistence.JoinTable;
import javax.persistence.ManyToMany;
import javax.persistence.ManyToOne;
import javax.persistence.OneToMany;
import javax.persistence.Table;
import javax.persistence.Temporal;
import javax.persistence.TemporalType;

/**
 * Abonne generated by hbm2java
 */
@Entity
@Table(name = "abonne", catalog = "itinelib")
public class Abonne implements java.io.Serializable {

	private Integer idabonne;
	private Ville ville;
	private String nomabonne;
	private String prenomabonne;
	private String adresse;
	private String tel;
	private Date datenaissance;
	private String sexe;
	private String titulairecompte;
	private String codebanque;
	private String codeagence;
	private String numerocompte;
	private String clefrib;
	private Set<Utilisateur> utilisateurs = new HashSet<Utilisateur>(0);
	private Set<Abonnement> abonnements = new HashSet<Abonnement>(0);
	private Set<Categoriepermis> categoriepermises = new HashSet<Categoriepermis>(
			0);

	public Abonne() {
	}

	public Abonne(Ville ville, String nomabonne, String prenomabonne,
			String adresse, String tel, Date datenaissance, String sexe,
			String titulairecompte, String codebanque, String codeagence,
			String numerocompte, String clefrib) {
		this.ville = ville;
		this.nomabonne = nomabonne;
		this.prenomabonne = prenomabonne;
		this.adresse = adresse;
		this.tel = tel;
		this.datenaissance = datenaissance;
		this.sexe = sexe;
		this.titulairecompte = titulairecompte;
		this.codebanque = codebanque;
		this.codeagence = codeagence;
		this.numerocompte = numerocompte;
		this.clefrib = clefrib;
	}

	public Abonne(Ville ville, String nomabonne, String prenomabonne,
			String adresse, String tel, Date datenaissance, String sexe,
			String titulairecompte, String codebanque, String codeagence,
			String numerocompte, String clefrib, Set<Utilisateur> utilisateurs,
			Set<Abonnement> abonnements, Set<Categoriepermis> categoriepermises) {
		this.ville = ville;
		this.nomabonne = nomabonne;
		this.prenomabonne = prenomabonne;
		this.adresse = adresse;
		this.tel = tel;
		this.datenaissance = datenaissance;
		this.sexe = sexe;
		this.titulairecompte = titulairecompte;
		this.codebanque = codebanque;
		this.codeagence = codeagence;
		this.numerocompte = numerocompte;
		this.clefrib = clefrib;
		this.utilisateurs = utilisateurs;
		this.abonnements = abonnements;
		this.categoriepermises = categoriepermises;
	}

	@Id
	@GeneratedValue(strategy = IDENTITY)
	@Column(name = "IDABONNE", unique = true, nullable = false)
	public Integer getIdabonne() {
		return this.idabonne;
	}

	public void setIdabonne(Integer idabonne) {
		this.idabonne = idabonne;
	}

	@ManyToOne()
	@JoinColumn(name = "IDVILLE", nullable = false)
	public Ville getVille() {
		return this.ville;
	}

	public void setVille(Ville ville) {
		this.ville = ville;
	}

	@Column(name = "NOMABONNE", nullable = false, length = 50)
	public String getNomabonne() {
		return this.nomabonne;
	}

	public void setNomabonne(String nomabonne) {
		this.nomabonne = nomabonne;
	}

	@Column(name = "PRENOMABONNE", nullable = false, length = 50)
	public String getPrenomabonne() {
		return this.prenomabonne;
	}

	public void setPrenomabonne(String prenomabonne) {
		this.prenomabonne = prenomabonne;
	}

	@Column(name = "ADRESSE", nullable = false, length = 200)
	public String getAdresse() {
		return this.adresse;
	}

	public void setAdresse(String adresse) {
		this.adresse = adresse;
	}

	@Column(name = "TEL", nullable = false, length = 50)
	public String getTel() {
		return this.tel;
	}

	public void setTel(String tel) {
		this.tel = tel;
	}

	@Temporal(TemporalType.DATE)
	@Column(name = "DATENAISSANCE", nullable = false, length = 10)
	public Date getDatenaissance() {
		return this.datenaissance;
	}

	public void setDatenaissance(Date datenaissance) {
		this.datenaissance = datenaissance;
	}

	@Column(name = "SEXE", nullable = false, length = 1)
	public String getSexe() {
		return this.sexe;
	}

	public void setSexe(String sexe) {
		this.sexe = sexe;
	}

	@Column(name = "TITULAIRECOMPTE", nullable = false, length = 50)
	public String getTitulairecompte() {
		return this.titulairecompte;
	}

	public void setTitulairecompte(String titulairecompte) {
		this.titulairecompte = titulairecompte;
	}

	@Column(name = "CODEBANQUE", nullable = false, length = 30)
	public String getCodebanque() {
		return this.codebanque;
	}

	public void setCodebanque(String codebanque) {
		this.codebanque = codebanque;
	}

	@Column(name = "CODEAGENCE", nullable = false, length = 30)
	public String getCodeagence() {
		return this.codeagence;
	}

	public void setCodeagence(String codeagence) {
		this.codeagence = codeagence;
	}

	@Column(name = "NUMEROCOMPTE", nullable = false, length = 30)
	public String getNumerocompte() {
		return this.numerocompte;
	}

	public void setNumerocompte(String numerocompte) {
		this.numerocompte = numerocompte;
	}

	@Column(name = "CLEFRIB", nullable = false, length = 30)
	public String getClefrib() {
		return this.clefrib;
	}

	public void setClefrib(String clefrib) {
		this.clefrib = clefrib;
	}

	@OneToMany(fetch = FetchType.EAGER, mappedBy = "abonne")
	public Set<Utilisateur> getUtilisateurs() {
		return this.utilisateurs;
	}

	public void setUtilisateurs(Set<Utilisateur> utilisateurs) {
		this.utilisateurs = utilisateurs;
	}

	@OneToMany(fetch = FetchType.EAGER, mappedBy = "abonne")
	public Set<Abonnement> getAbonnements() {
		return this.abonnements;
	}

	public void setAbonnements(Set<Abonnement> abonnements) {
		this.abonnements = abonnements;
	}

	@ManyToMany()
	@JoinTable(name = "detenir", catalog = "itinelib", joinColumns = { @JoinColumn(name = "IDABONNE", nullable = false, updatable = false) }, inverseJoinColumns = { @JoinColumn(name = "IDCATEGORIEPERMIS", nullable = false, updatable = false) })
	public Set<Categoriepermis> getCategoriepermises() {
		return this.categoriepermises;
	}

	public void setCategoriepermises(Set<Categoriepermis> categoriepermises) {
		this.categoriepermises = categoriepermises;
	}

}
