package fr.afcepf.ai83.itinelib.model;

// Generated 29 juin 2012 16:59:41 by Hibernate Tools 3.4.0.Beta1

import java.util.HashSet;
import java.util.Set;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.GeneratedValue;
import static javax.persistence.GenerationType.IDENTITY;
import javax.persistence.Id;
import javax.persistence.JoinColumn;
import javax.persistence.JoinTable;
import javax.persistence.ManyToMany;
import javax.persistence.ManyToOne;
import javax.persistence.OneToMany;
import javax.persistence.Table;

/**
 * Categorievehicule generated by hbm2java
 */
@Entity
@Table(name = "categorievehicule", catalog = "itinelib")
public class Categorievehicule implements java.io.Serializable {

	private Integer idcategorievehicule;
	private Categoriepermis categoriepermis;
	private String nomtypevehicule;
	private Float tauxhoraire;
	private Float tauxkilometrique;
	private Set<Vehicule> vehicules = new HashSet<Vehicule>(0);
	private Set<Typeabonnement> typeabonnements = new HashSet<Typeabonnement>(0);
	private Set<Emplacement> emplacements = new HashSet<Emplacement>(0);

	public Categorievehicule() {
	}

	public Categorievehicule(Categoriepermis categoriepermis,
			String nomtypevehicule, Float tauxhoraire, Float tauxkilometrique,
			Set<Vehicule> vehicules, Set<Typeabonnement> typeabonnements,
			Set<Emplacement> emplacements) {
		this.categoriepermis = categoriepermis;
		this.nomtypevehicule = nomtypevehicule;
		this.tauxhoraire = tauxhoraire;
		this.tauxkilometrique = tauxkilometrique;
		this.vehicules = vehicules;
		this.typeabonnements = typeabonnements;
		this.emplacements = emplacements;
	}

	@Id
	@GeneratedValue(strategy = IDENTITY)
	@Column(name = "IDCATEGORIEVEHICULE", unique = true, nullable = false)
	public Integer getIdcategorievehicule() {
		return this.idcategorievehicule;
	}

	public void setIdcategorievehicule(Integer idcategorievehicule) {
		this.idcategorievehicule = idcategorievehicule;
	}

	@ManyToOne()
	@JoinColumn(name = "IDCATEGORIEPERMIS")
	public Categoriepermis getCategoriepermis() {
		return this.categoriepermis;
	}

	public void setCategoriepermis(Categoriepermis categoriepermis) {
		this.categoriepermis = categoriepermis;
	}

	@Column(name = "NOMTYPEVEHICULE", length = 50)
	public String getNomtypevehicule() {
		return this.nomtypevehicule;
	}

	public void setNomtypevehicule(String nomtypevehicule) {
		this.nomtypevehicule = nomtypevehicule;
	}

	@Column(name = "TAUXHORAIRE", precision = 12, scale = 0)
	public Float getTauxhoraire() {
		return this.tauxhoraire;
	}

	public void setTauxhoraire(Float tauxhoraire) {
		this.tauxhoraire = tauxhoraire;
	}

	@Column(name = "TAUXKILOMETRIQUE", precision = 12, scale = 0)
	public Float getTauxkilometrique() {
		return this.tauxkilometrique;
	}

	public void setTauxkilometrique(Float tauxkilometrique) {
		this.tauxkilometrique = tauxkilometrique;
	}

	@OneToMany(mappedBy = "categorievehicule")
	public Set<Vehicule> getVehicules() {
		return this.vehicules;
	}

	public void setVehicules(Set<Vehicule> vehicules) {
		this.vehicules = vehicules;
	}

	@ManyToMany()
	@JoinTable(name = "inclure", catalog = "itinelib", joinColumns = { @JoinColumn(name = "IDCATEGORIEVEHICULE", nullable = false, updatable = false) }, inverseJoinColumns = { @JoinColumn(name = "IDTYPE", nullable = false, updatable = false) })
	public Set<Typeabonnement> getTypeabonnements() {
		return this.typeabonnements;
	}

	public void setTypeabonnements(Set<Typeabonnement> typeabonnements) {
		this.typeabonnements = typeabonnements;
	}

	@OneToMany(mappedBy = "categorievehicule")
	public Set<Emplacement> getEmplacements() {
		return this.emplacements;
	}

	public void setEmplacements(Set<Emplacement> emplacements) {
		this.emplacements = emplacements;
	}

}
