package fr.afcepf.ai83.itinelib.model;

// Generated 29 juin 2012 16:59:41 by Hibernate Tools 3.4.0.Beta1

import java.util.HashSet;
import java.util.Set;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.GeneratedValue;
import static javax.persistence.GenerationType.IDENTITY;
import javax.persistence.Id;
import javax.persistence.ManyToMany;
import javax.persistence.OneToMany;
import javax.persistence.Table;

/**
 * Categoriepermis generated by hbm2java
 */
@Entity
@Table(name = "categoriepermis", catalog = "itinelib")
public class Categoriepermis implements java.io.Serializable {

	private Integer idcategoriepermis;
	private String nompermis;
	private Set<Abonne> abonnes = new HashSet<Abonne>(0);
	private Set<Categorievehicule> categorievehicules = new HashSet<Categorievehicule>(
			0);

	public Categoriepermis() {
	}

	public Categoriepermis(String nompermis) {
		this.nompermis = nompermis;
	}

	public Categoriepermis(String nompermis, Set<Abonne> abonnes,
			Set<Categorievehicule> categorievehicules) {
		this.nompermis = nompermis;
		this.abonnes = abonnes;
		this.categorievehicules = categorievehicules;
	}

	@Id
	@GeneratedValue(strategy = IDENTITY)
	@Column(name = "IDCATEGORIEPERMIS", unique = true, nullable = false)
	public Integer getIdcategoriepermis() {
		return this.idcategoriepermis;
	}

	public void setIdcategoriepermis(Integer idcategoriepermis) {
		this.idcategoriepermis = idcategoriepermis;
	}

	@Column(name = "NOMPERMIS", nullable = false, length = 20)
	public String getNompermis() {
		return this.nompermis;
	}

	public void setNompermis(String nompermis) {
		this.nompermis = nompermis;
	}

	@ManyToMany(mappedBy = "categoriepermises")
	public Set<Abonne> getAbonnes() {
		return this.abonnes;
	}

	public void setAbonnes(Set<Abonne> abonnes) {
		this.abonnes = abonnes;
	}

	@OneToMany( mappedBy = "categoriepermis")
	public Set<Categorievehicule> getCategorievehicules() {
		return this.categorievehicules;
	}

	public void setCategorievehicules(Set<Categorievehicule> categorievehicules) {
		this.categorievehicules = categorievehicules;
	}

}
