package fr.afcepf.ai83.itinelib.model;

// Generated 29 juin 2012 16:59:41 by Hibernate Tools 3.4.0.Beta1

import java.util.HashSet;
import java.util.Set;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.GeneratedValue;
import static javax.persistence.GenerationType.IDENTITY;
import javax.persistence.Id;
import javax.persistence.OneToMany;
import javax.persistence.Table;

/**
 * Employe generated by hbm2java
 */
@Entity
@Table(name = "employe", catalog = "itinelib")
public class Employe implements java.io.Serializable {

	private Integer idemploye;
	private String nomemploye;
	private String prenomemploye;
	private String service;
	private Set<Utilisateur> utilisateurs = new HashSet<Utilisateur>(0);
	private Set<Registre> registres = new HashSet<Registre>(0);

	public Employe() {
	}

	public Employe(String nomemploye, String prenomemploye) {
		this.nomemploye = nomemploye;
		this.prenomemploye = prenomemploye;
	}

	public Employe(String nomemploye, String prenomemploye, String service,
			Set<Utilisateur> utilisateurs, Set<Registre> registres) {
		this.nomemploye = nomemploye;
		this.prenomemploye = prenomemploye;
		this.service = service;
		this.utilisateurs = utilisateurs;
		this.registres = registres;
	}

	@Id
	@GeneratedValue(strategy = IDENTITY)
	@Column(name = "IDEMPLOYE", unique = true, nullable = false)
	public Integer getIdemploye() {
		return this.idemploye;
	}

	public void setIdemploye(Integer idemploye) {
		this.idemploye = idemploye;
	}

	@Column(name = "NOMEMPLOYE", nullable = false, length = 45)
	public String getNomemploye() {
		return this.nomemploye;
	}

	public void setNomemploye(String nomemploye) {
		this.nomemploye = nomemploye;
	}

	@Column(name = "PRENOMEMPLOYE", nullable = false, length = 45)
	public String getPrenomemploye() {
		return this.prenomemploye;
	}

	public void setPrenomemploye(String prenomemploye) {
		this.prenomemploye = prenomemploye;
	}

	@Column(name = "SERVICE", length = 45)
	public String getService() {
		return this.service;
	}

	public void setService(String service) {
		this.service = service;
	}

	@OneToMany(mappedBy = "employe")
	public Set<Utilisateur> getUtilisateurs() {
		return this.utilisateurs;
	}

	public void setUtilisateurs(Set<Utilisateur> utilisateurs) {
		this.utilisateurs = utilisateurs;
	}

	@OneToMany(mappedBy = "employe")
	public Set<Registre> getRegistres() {
		return this.registres;
	}

	public void setRegistres(Set<Registre> registres) {
		this.registres = registres;
	}

}
