package fr.afcepf.ai83.itinelib.model;

// Generated 29 juin 2012 16:59:41 by Hibernate Tools 3.4.0.Beta1

import java.util.Date;
import javax.persistence.Column;
import javax.persistence.Embeddable;

/**
 * HistoriqueabonnementId generated by hbm2java
 */
@Embeddable
public class HistoriqueabonnementId implements java.io.Serializable {

	private int idtypefinabonnement;
	private int idtypedebutabonnement;
	private int idabonnement;
	private Date dhhistorique;

	public HistoriqueabonnementId() {
	}

	public HistoriqueabonnementId(int idtypefinabonnement,
			int idtypedebutabonnement, int idabonnement, Date dhhistorique) {
		this.idtypefinabonnement = idtypefinabonnement;
		this.idtypedebutabonnement = idtypedebutabonnement;
		this.idabonnement = idabonnement;
		this.dhhistorique = dhhistorique;
	}

	@Column(name = "IDTYPEFINABONNEMENT", nullable = false)
	public int getIdtypefinabonnement() {
		return this.idtypefinabonnement;
	}

	public void setIdtypefinabonnement(int idtypefinabonnement) {
		this.idtypefinabonnement = idtypefinabonnement;
	}

	@Column(name = "IDTYPEDEBUTABONNEMENT", nullable = false)
	public int getIdtypedebutabonnement() {
		return this.idtypedebutabonnement;
	}

	public void setIdtypedebutabonnement(int idtypedebutabonnement) {
		this.idtypedebutabonnement = idtypedebutabonnement;
	}

	@Column(name = "IDABONNEMENT", nullable = false)
	public int getIdabonnement() {
		return this.idabonnement;
	}

	public void setIdabonnement(int idabonnement) {
		this.idabonnement = idabonnement;
	}

	@Column(name = "DHHISTORIQUE", nullable = false, length = 19)
	public Date getDhhistorique() {
		return this.dhhistorique;
	}

	public void setDhhistorique(Date dhhistorique) {
		this.dhhistorique = dhhistorique;
	}

	public boolean equals(Object other) {
		if ((this == other))
			return true;
		if ((other == null))
			return false;
		if (!(other instanceof HistoriqueabonnementId))
			return false;
		HistoriqueabonnementId castOther = (HistoriqueabonnementId) other;

		return (this.getIdtypefinabonnement() == castOther
				.getIdtypefinabonnement())
				&& (this.getIdtypedebutabonnement() == castOther
						.getIdtypedebutabonnement())
				&& (this.getIdabonnement() == castOther.getIdabonnement())
				&& ((this.getDhhistorique() == castOther.getDhhistorique()) || (this
						.getDhhistorique() != null
						&& castOther.getDhhistorique() != null && this
						.getDhhistorique().equals(castOther.getDhhistorique())));
	}

	public int hashCode() {
		int result = 17;

		result = 37 * result + this.getIdtypefinabonnement();
		result = 37 * result + this.getIdtypedebutabonnement();
		result = 37 * result + this.getIdabonnement();
		result = 37
				* result
				+ (getDhhistorique() == null ? 0 : this.getDhhistorique()
						.hashCode());
		return result;
	}

}
