package fr.afcepf.ai83.itinelib.model;

// Generated 29 juin 2012 16:59:41 by Hibernate Tools 3.4.0.Beta1

import javax.persistence.AttributeOverride;
import javax.persistence.AttributeOverrides;
import javax.persistence.Column;
import javax.persistence.EmbeddedId;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.Table;

/**
 * Historiqueabonnement generated by hbm2java
 */
@Entity
@Table(name = "historiqueabonnement", catalog = "itinelib")
public class Historiqueabonnement implements java.io.Serializable {

	private HistoriqueabonnementId id;
	private Typeabonnement typeabonnementByIdtypedebutabonnement;
	private Typeabonnement typeabonnementByIdtypefinabonnement;
	private Abonnement abonnement;

	public Historiqueabonnement() {
	}

	public Historiqueabonnement(HistoriqueabonnementId id,
			Typeabonnement typeabonnementByIdtypedebutabonnement,
			Typeabonnement typeabonnementByIdtypefinabonnement,
			Abonnement abonnement) {
		this.id = id;
		this.typeabonnementByIdtypedebutabonnement = typeabonnementByIdtypedebutabonnement;
		this.typeabonnementByIdtypefinabonnement = typeabonnementByIdtypefinabonnement;
		this.abonnement = abonnement;
	}

	@EmbeddedId
	@AttributeOverrides({
			@AttributeOverride(name = "idtypefinabonnement", column = @Column(name = "IDTYPEFINABONNEMENT", nullable = false)),
			@AttributeOverride(name = "idtypedebutabonnement", column = @Column(name = "IDTYPEDEBUTABONNEMENT", nullable = false)),
			@AttributeOverride(name = "idabonnement", column = @Column(name = "IDABONNEMENT", nullable = false)),
			@AttributeOverride(name = "dhhistorique", column = @Column(name = "DHHISTORIQUE", nullable = false, length = 19)) })
	public HistoriqueabonnementId getId() {
		return this.id;
	}

	public void setId(HistoriqueabonnementId id) {
		this.id = id;
	}

	@ManyToOne()
	@JoinColumn(name = "IDTYPEDEBUTABONNEMENT", nullable = false, insertable = false, updatable = false)
	public Typeabonnement getTypeabonnementByIdtypedebutabonnement() {
		return this.typeabonnementByIdtypedebutabonnement;
	}

	public void setTypeabonnementByIdtypedebutabonnement(
			Typeabonnement typeabonnementByIdtypedebutabonnement) {
		this.typeabonnementByIdtypedebutabonnement = typeabonnementByIdtypedebutabonnement;
	}

	@ManyToOne()
	@JoinColumn(name = "IDTYPEFINABONNEMENT", nullable = false, insertable = false, updatable = false)
	public Typeabonnement getTypeabonnementByIdtypefinabonnement() {
		return this.typeabonnementByIdtypefinabonnement;
	}

	public void setTypeabonnementByIdtypefinabonnement(
			Typeabonnement typeabonnementByIdtypefinabonnement) {
		this.typeabonnementByIdtypefinabonnement = typeabonnementByIdtypefinabonnement;
	}

	@ManyToOne()
	@JoinColumn(name = "IDABONNEMENT", nullable = false, insertable = false, updatable = false)
	public Abonnement getAbonnement() {
		return this.abonnement;
	}

	public void setAbonnement(Abonnement abonnement) {
		this.abonnement = abonnement;
	}

}
