package fr.afcepf.ai83.itinelib.model;

// Generated 29 juin 2012 16:59:41 by Hibernate Tools 3.4.0.Beta1

import java.util.HashSet;
import java.util.Set;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.GeneratedValue;
import static javax.persistence.GenerationType.IDENTITY;
import javax.persistence.Id;
import javax.persistence.OneToMany;
import javax.persistence.Table;

/**
 * Pointlocation generated by hbm2java
 */
@Entity
@Table(name = "pointlocation", catalog = "itinelib")
public class Pointlocation implements java.io.Serializable {

	private Integer idpointlocation;
	private String nompointlocation;
	private double lattitude;
	private double longitude;
	private Set<Registre> registresForPoiIdpointlocation = new HashSet<Registre>(
			0);
	private Set<Emplacement> emplacements = new HashSet<Emplacement>(0);
	private Set<Registre> registresForIdpointlocation = new HashSet<Registre>(0);

	public Pointlocation() {
	}

	public Pointlocation(String nompointlocation, double lattitude,
			double longitude) {
		this.nompointlocation = nompointlocation;
		this.lattitude = lattitude;
		this.longitude = longitude;
	}

	public Pointlocation(String nompointlocation, double lattitude,
			double longitude, Set<Registre> registresForPoiIdpointlocation,
			Set<Emplacement> emplacements,
			Set<Registre> registresForIdpointlocation) {
		this.nompointlocation = nompointlocation;
		this.lattitude = lattitude;
		this.longitude = longitude;
		this.registresForPoiIdpointlocation = registresForPoiIdpointlocation;
		this.emplacements = emplacements;
		this.registresForIdpointlocation = registresForIdpointlocation;
	}

	@Id
	@GeneratedValue(strategy = IDENTITY)
	@Column(name = "IDPOINTLOCATION", unique = true, nullable = false)
	public Integer getIdpointlocation() {
		return this.idpointlocation;
	}

	public void setIdpointlocation(Integer idpointlocation) {
		this.idpointlocation = idpointlocation;
	}

	@Column(name = "NOMPOINTLOCATION", nullable = false, length = 50)
	public String getNompointlocation() {
		return this.nompointlocation;
	}

	public void setNompointlocation(String nompointlocation) {
		this.nompointlocation = nompointlocation;
	}

	@Column(name = "LATTITUDE", nullable = false, precision = 22, scale = 0)
	public double getLattitude() {
		return this.lattitude;
	}

	public void setLattitude(double lattitude) {
		this.lattitude = lattitude;
	}

	@Column(name = "LONGITUDE", nullable = false, precision = 22, scale = 0)
	public double getLongitude() {
		return this.longitude;
	}

	public void setLongitude(double longitude) {
		this.longitude = longitude;
	}

	@OneToMany(mappedBy = "pointlocationByPoiIdpointlocation")
	public Set<Registre> getRegistresForPoiIdpointlocation() {
		return this.registresForPoiIdpointlocation;
	}

	public void setRegistresForPoiIdpointlocation(
			Set<Registre> registresForPoiIdpointlocation) {
		this.registresForPoiIdpointlocation = registresForPoiIdpointlocation;
	}

	@OneToMany(mappedBy = "pointlocation")
	public Set<Emplacement> getEmplacements() {
		return this.emplacements;
	}

	public void setEmplacements(Set<Emplacement> emplacements) {
		this.emplacements = emplacements;
	}

	@OneToMany(mappedBy = "pointlocationByIdpointlocation")
	public Set<Registre> getRegistresForIdpointlocation() {
		return this.registresForIdpointlocation;
	}

	public void setRegistresForIdpointlocation(
			Set<Registre> registresForIdpointlocation) {
		this.registresForIdpointlocation = registresForIdpointlocation;
	}

}
