package fr.afcepf.ai83.itinelib.model;

// Generated 29 juin 2012 16:59:41 by Hibernate Tools 3.4.0.Beta1

import java.util.Date;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.GeneratedValue;
import static javax.persistence.GenerationType.IDENTITY;
import javax.persistence.Id;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.Table;
import javax.persistence.Temporal;
import javax.persistence.TemporalType;

/**
 * Registre generated by hbm2java
 */
@Entity
@Table(name = "registre", catalog = "itinelib")
public class Registre implements java.io.Serializable {

	private Integer idregistre;
	private Emplacement emplacement;
	private Pointlocation pointlocationByPoiIdpointlocation;
	private Employe employe;
	private Vehicule vehicule;
	private Pointlocation pointlocationByIdpointlocation;
	private Abonnement abonnement;
	private Resaglobale resaglobale;
	private Date dhdebutlocation;
	private Date dhretourlocation;
	private Date dharriveeclient;
	private Date dhreservationprevue;
	private Date dhannulationreservation;
	private Date dhdebutdeplacement;
	private Date dhretourdeplacement;

	public Registre() {
	}

	public Registre(Pointlocation pointlocationByIdpointlocation) {
		this.pointlocationByIdpointlocation = pointlocationByIdpointlocation;
	}

	public Registre(Emplacement emplacement,
			Pointlocation pointlocationByPoiIdpointlocation, Employe employe,
			Vehicule vehicule, Pointlocation pointlocationByIdpointlocation,
			Abonnement abonnement, Resaglobale resaglobale,
			Date dhdebutlocation, Date dhretourlocation, Date dharriveeclient,
			Date dhreservationprevue, Date dhannulationreservation,
			Date dhdebutdeplacement, Date dhretourdeplacement) {
		this.emplacement = emplacement;
		this.pointlocationByPoiIdpointlocation = pointlocationByPoiIdpointlocation;
		this.employe = employe;
		this.vehicule = vehicule;
		this.pointlocationByIdpointlocation = pointlocationByIdpointlocation;
		this.abonnement = abonnement;
		this.resaglobale = resaglobale;
		this.dhdebutlocation = dhdebutlocation;
		this.dhretourlocation = dhretourlocation;
		this.dharriveeclient = dharriveeclient;
		this.dhreservationprevue = dhreservationprevue;
		this.dhannulationreservation = dhannulationreservation;
		this.dhdebutdeplacement = dhdebutdeplacement;
		this.dhretourdeplacement = dhretourdeplacement;
	}

	@Id
	@GeneratedValue(strategy = IDENTITY)
	@Column(name = "IDREGISTRE", unique = true, nullable = false)
	public Integer getIdregistre() {
		return this.idregistre;
	}

	public void setIdregistre(Integer idregistre) {
		this.idregistre = idregistre;
	}

	@ManyToOne()
	@JoinColumn(name = "IDEMPLACEMENT")
	public Emplacement getEmplacement() {
		return this.emplacement;
	}

	public void setEmplacement(Emplacement emplacement) {
		this.emplacement = emplacement;
	}

	@ManyToOne()
	@JoinColumn(name = "POI_IDPOINTLOCATION")
	public Pointlocation getPointlocationByPoiIdpointlocation() {
		return this.pointlocationByPoiIdpointlocation;
	}

	public void setPointlocationByPoiIdpointlocation(
			Pointlocation pointlocationByPoiIdpointlocation) {
		this.pointlocationByPoiIdpointlocation = pointlocationByPoiIdpointlocation;
	}

	@ManyToOne()
	@JoinColumn(name = "IDEMPLOYE")
	public Employe getEmploye() {
		return this.employe;
	}

	public void setEmploye(Employe employe) {
		this.employe = employe;
	}

	@ManyToOne()
	@JoinColumn(name = "IDVEHICULE")
	public Vehicule getVehicule() {
		return this.vehicule;
	}

	public void setVehicule(Vehicule vehicule) {
		this.vehicule = vehicule;
	}

	@ManyToOne()
	@JoinColumn(name = "IDPOINTLOCATION", nullable = false)
	public Pointlocation getPointlocationByIdpointlocation() {
		return this.pointlocationByIdpointlocation;
	}

	public void setPointlocationByIdpointlocation(
			Pointlocation pointlocationByIdpointlocation) {
		this.pointlocationByIdpointlocation = pointlocationByIdpointlocation;
	}

	@ManyToOne()
	@JoinColumn(name = "IDABONNEMENT")
	public Abonnement getAbonnement() {
		return this.abonnement;
	}

	public void setAbonnement(Abonnement abonnement) {
		this.abonnement = abonnement;
	}

	@ManyToOne()
	@JoinColumn(name = "IDRESAGLOBALE")
	public Resaglobale getResaglobale() {
		return this.resaglobale;
	}

	public void setResaglobale(Resaglobale resaglobale) {
		this.resaglobale = resaglobale;
	}

	@Temporal(TemporalType.TIMESTAMP)
	@Column(name = "DHDEBUTLOCATION", length = 19)
	public Date getDhdebutlocation() {
		return this.dhdebutlocation;
	}

	public void setDhdebutlocation(Date dhdebutlocation) {
		this.dhdebutlocation = dhdebutlocation;
	}

	@Temporal(TemporalType.TIMESTAMP)
	@Column(name = "DHRETOURLOCATION", length = 19)
	public Date getDhretourlocation() {
		return this.dhretourlocation;
	}

	public void setDhretourlocation(Date dhretourlocation) {
		this.dhretourlocation = dhretourlocation;
	}

	@Temporal(TemporalType.TIMESTAMP)
	@Column(name = "DHARRIVEECLIENT", length = 19)
	public Date getDharriveeclient() {
		return this.dharriveeclient;
	}

	public void setDharriveeclient(Date dharriveeclient) {
		this.dharriveeclient = dharriveeclient;
	}

	@Temporal(TemporalType.TIMESTAMP)
	@Column(name = "DHRESERVATIONPREVUE", length = 19)
	public Date getDhreservationprevue() {
		return this.dhreservationprevue;
	}

	public void setDhreservationprevue(Date dhreservationprevue) {
		this.dhreservationprevue = dhreservationprevue;
	}

	@Temporal(TemporalType.TIMESTAMP)
	@Column(name = "DHANNULATIONRESERVATION", length = 19)
	public Date getDhannulationreservation() {
		return this.dhannulationreservation;
	}

	public void setDhannulationreservation(Date dhannulationreservation) {
		this.dhannulationreservation = dhannulationreservation;
	}

	@Temporal(TemporalType.TIMESTAMP)
	@Column(name = "DHDEBUTDEPLACEMENT", length = 19)
	public Date getDhdebutdeplacement() {
		return this.dhdebutdeplacement;
	}

	public void setDhdebutdeplacement(Date dhdebutdeplacement) {
		this.dhdebutdeplacement = dhdebutdeplacement;
	}

	@Temporal(TemporalType.TIMESTAMP)
	@Column(name = "DHRETOURDEPLACEMENT", length = 19)
	public Date getDhretourdeplacement() {
		return this.dhretourdeplacement;
	}

	public void setDhretourdeplacement(Date dhretourdeplacement) {
		this.dhretourdeplacement = dhretourdeplacement;
	}

}
