package fr.afcepf.ai83.itinelib.model;

// Generated 29 juin 2012 16:59:41 by Hibernate Tools 3.4.0.Beta1

import java.util.Date;
import java.util.HashSet;
import java.util.Set;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.GeneratedValue;
import static javax.persistence.GenerationType.IDENTITY;
import javax.persistence.Id;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.OneToMany;
import javax.persistence.Table;
import javax.persistence.Temporal;
import javax.persistence.TemporalType;

/**
 * Resaglobale generated by hbm2java
 */
@Entity
@Table(name = "resaglobale", catalog = "itinelib")
public class Resaglobale implements java.io.Serializable {

	private Integer idresaglobale;
	private Abonnement abonnement;
	private Date dhcreation;
	private Date dhannulation;
	private Set<Registre> registres = new HashSet<Registre>(0);

	public Resaglobale() {
	}

	public Resaglobale(Abonnement abonnement, Date dhcreation) {
		this.abonnement = abonnement;
		this.dhcreation = dhcreation;
	}

	public Resaglobale(Abonnement abonnement, Date dhcreation,
			Date dhannulation, Set<Registre> registres) {
		this.abonnement = abonnement;
		this.dhcreation = dhcreation;
		this.dhannulation = dhannulation;
		this.registres = registres;
	}

	@Id
	@GeneratedValue(strategy = IDENTITY)
	@Column(name = "IDRESAGLOBALE", unique = true, nullable = false)
	public Integer getIdresaglobale() {
		return this.idresaglobale;
	}

	public void setIdresaglobale(Integer idresaglobale) {
		this.idresaglobale = idresaglobale;
	}

	@ManyToOne()
	@JoinColumn(name = "IDABONNEMENT", nullable = false)
	public Abonnement getAbonnement() {
		return this.abonnement;
	}

	public void setAbonnement(Abonnement abonnement) {
		this.abonnement = abonnement;
	}

	@Temporal(TemporalType.TIMESTAMP)
	@Column(name = "DHCREATION", nullable = false, length = 19)
	public Date getDhcreation() {
		return this.dhcreation;
	}

	public void setDhcreation(Date dhcreation) {
		this.dhcreation = dhcreation;
	}

	@Temporal(TemporalType.TIMESTAMP)
	@Column(name = "DHANNULATION", length = 19)
	public Date getDhannulation() {
		return this.dhannulation;
	}

	public void setDhannulation(Date dhannulation) {
		this.dhannulation = dhannulation;
	}

	@OneToMany(mappedBy = "resaglobale")
	public Set<Registre> getRegistres() {
		return this.registres;
	}

	public void setRegistres(Set<Registre> registres) {
		this.registres = registres;
	}

}
