package fr.afcepf.ai83.itinelib.model;

// Generated 29 juin 2012 16:59:41 by Hibernate Tools 3.4.0.Beta1

import java.util.HashSet;
import java.util.Set;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.GeneratedValue;
import static javax.persistence.GenerationType.IDENTITY;
import javax.persistence.Id;
import javax.persistence.ManyToMany;
import javax.persistence.OneToMany;
import javax.persistence.Table;

/**
 * Typeabonnement generated by hbm2java
 */
@Entity
@Table(name = "typeabonnement", catalog = "itinelib")
public class Typeabonnement implements java.io.Serializable {

	private Integer idtype;
	private String nomabonnement;
	private float cout;
	private Set<Historiqueabonnement> historiqueabonnementsForIdtypedebutabonnement = new HashSet<Historiqueabonnement>(
			0);
	private Set<Categorievehicule> categorievehicules = new HashSet<Categorievehicule>(
			0);
	private Set<Historiqueabonnement> historiqueabonnementsForIdtypefinabonnement = new HashSet<Historiqueabonnement>(
			0);
	private Set<Abonnement> abonnements = new HashSet<Abonnement>(0);

	public Typeabonnement() {
	}

	public Typeabonnement(String nomabonnement, float cout) {
		this.nomabonnement = nomabonnement;
		this.cout = cout;
	}

	public Typeabonnement(
			String nomabonnement,
			float cout,
			Set<Historiqueabonnement> historiqueabonnementsForIdtypedebutabonnement,
			Set<Categorievehicule> categorievehicules,
			Set<Historiqueabonnement> historiqueabonnementsForIdtypefinabonnement,
			Set<Abonnement> abonnements) {
		this.nomabonnement = nomabonnement;
		this.cout = cout;
		this.historiqueabonnementsForIdtypedebutabonnement = historiqueabonnementsForIdtypedebutabonnement;
		this.categorievehicules = categorievehicules;
		this.historiqueabonnementsForIdtypefinabonnement = historiqueabonnementsForIdtypefinabonnement;
		this.abonnements = abonnements;
	}

	@Id
	@GeneratedValue(strategy = IDENTITY)
	@Column(name = "IDTYPE", unique = true, nullable = false)
	public Integer getIdtype() {
		return this.idtype;
	}

	public void setIdtype(Integer idtype) {
		this.idtype = idtype;
	}

	@Column(name = "NOMABONNEMENT", nullable = false, length = 50)
	public String getNomabonnement() {
		return this.nomabonnement;
	}

	public void setNomabonnement(String nomabonnement) {
		this.nomabonnement = nomabonnement;
	}

	@Column(name = "COUT", nullable = false, precision = 12, scale = 0)
	public float getCout() {
		return this.cout;
	}

	public void setCout(float cout) {
		this.cout = cout;
	}

	@OneToMany(mappedBy = "typeabonnementByIdtypedebutabonnement")
	public Set<Historiqueabonnement> getHistoriqueabonnementsForIdtypedebutabonnement() {
		return this.historiqueabonnementsForIdtypedebutabonnement;
	}

	public void setHistoriqueabonnementsForIdtypedebutabonnement(
			Set<Historiqueabonnement> historiqueabonnementsForIdtypedebutabonnement) {
		this.historiqueabonnementsForIdtypedebutabonnement = historiqueabonnementsForIdtypedebutabonnement;
	}

	@ManyToMany(mappedBy = "typeabonnements")
	public Set<Categorievehicule> getCategorievehicules() {
		return this.categorievehicules;
	}

	public void setCategorievehicules(Set<Categorievehicule> categorievehicules) {
		this.categorievehicules = categorievehicules;
	}

	@OneToMany(mappedBy = "typeabonnementByIdtypefinabonnement")
	public Set<Historiqueabonnement> getHistoriqueabonnementsForIdtypefinabonnement() {
		return this.historiqueabonnementsForIdtypefinabonnement;
	}

	public void setHistoriqueabonnementsForIdtypefinabonnement(
			Set<Historiqueabonnement> historiqueabonnementsForIdtypefinabonnement) {
		this.historiqueabonnementsForIdtypefinabonnement = historiqueabonnementsForIdtypefinabonnement;
	}

	@OneToMany(mappedBy = "typeabonnement")
	public Set<Abonnement> getAbonnements() {
		return this.abonnements;
	}

	public void setAbonnements(Set<Abonnement> abonnements) {
		this.abonnements = abonnements;
	}

}
