package fr.afcepf.ai83.itinelib.model;

// Generated 29 juin 2012 16:59:41 by Hibernate Tools 3.4.0.Beta1

import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.GeneratedValue;
import static javax.persistence.GenerationType.IDENTITY;
import javax.persistence.Id;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.Table;

/**
 * Utilisateur generated by hbm2java
 */
@Entity
@Table(name = "utilisateur", catalog = "itinelib")
public class Utilisateur implements java.io.Serializable {

	private Integer idutilisateur;
	private Employe employe;
	private Abonne abonne;
	private String email;
	private String motdepassHash;
	private String motdepassSalt;
	private String role;

	public Utilisateur() {
	}

	public Utilisateur(String email, String motdepassHash,
			String motdepassSalt, String role) {
		this.email = email;
		this.motdepassHash = motdepassHash;
		this.motdepassSalt = motdepassSalt;
		this.role = role;
	}

	public Utilisateur(Employe employe, Abonne abonne, String email,
			String motdepassHash, String motdepassSalt, String role) {
		this.employe = employe;
		this.abonne = abonne;
		this.email = email;
		this.motdepassHash = motdepassHash;
		this.motdepassSalt = motdepassSalt;
		this.role = role;
	}

	@Id
	@GeneratedValue(strategy = IDENTITY)
	@Column(name = "IDUTILISATEUR", unique = true, nullable = false)
	public Integer getIdutilisateur() {
		return this.idutilisateur;
	}

	public void setIdutilisateur(Integer idutilisateur) {
		this.idutilisateur = idutilisateur;
	}

	@ManyToOne()
	@JoinColumn(name = "IDEMPLOYE")
	public Employe getEmploye() {
		return this.employe;
	}

	public void setEmploye(Employe employe) {
		this.employe = employe;
	}

	@ManyToOne()
	@JoinColumn(name = "IDABONNE")
	public Abonne getAbonne() {
		return this.abonne;
	}

	public void setAbonne(Abonne abonne) {
		this.abonne = abonne;
	}

	@Column(name = "EMAIL", nullable = false, length = 50)
	public String getEmail() {
		return this.email;
	}

	public void setEmail(String email) {
		this.email = email;
	}

	@Column(name = "MOTDEPASS_HASH", nullable = false, length = 100)
	public String getMotdepassHash() {
		return this.motdepassHash;
	}

	public void setMotdepassHash(String motdepassHash) {
		this.motdepassHash = motdepassHash;
	}

	@Column(name = "MOTDEPASS_SALT", nullable = false, length = 100)
	public String getMotdepassSalt() {
		return this.motdepassSalt;
	}

	public void setMotdepassSalt(String motdepassSalt) {
		this.motdepassSalt = motdepassSalt;
	}

	@Column(name = "ROLE", nullable = false, length = 50)
	public String getRole() {
		return this.role;
	}

	public void setRole(String role) {
		this.role = role;
	}

}
