package fr.afcepf.ai83.itinelib.model;

// Generated 29 juin 2012 16:59:41 by Hibernate Tools 3.4.0.Beta1

import java.util.HashSet;
import java.util.Set;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.GeneratedValue;
import static javax.persistence.GenerationType.IDENTITY;
import javax.persistence.Id;
import javax.persistence.OneToMany;
import javax.persistence.Table;

/**
 * Ville generated by hbm2java
 */
@Entity
@Table(name = "ville", catalog = "itinelib")
public class Ville implements java.io.Serializable {

	private Integer idville;
	private String nomville;
	private String codepostal;
	private Set<Abonne> abonnes = new HashSet<Abonne>(0);

	public Ville() {
	}

	public Ville(String nomville, String codepostal) {
		this.nomville = nomville;
		this.codepostal = codepostal;
	}

	public Ville(String nomville, String codepostal, Set<Abonne> abonnes) {
		this.nomville = nomville;
		this.codepostal = codepostal;
		this.abonnes = abonnes;
	}

	@Id
	@GeneratedValue(strategy = IDENTITY)
	@Column(name = "IDVILLE", unique = true, nullable = false)
	public Integer getIdville() {
		return this.idville;
	}

	public void setIdville(Integer idville) {
		this.idville = idville;
	}

	@Column(name = "NOMVILLE", nullable = false, length = 50)
	public String getNomville() {
		return this.nomville;
	}

	public void setNomville(String nomville) {
		this.nomville = nomville;
	}

	@Column(name = "CODEPOSTAL", nullable = false, length = 20)
	public String getCodepostal() {
		return this.codepostal;
	}

	public void setCodepostal(String codepostal) {
		this.codepostal = codepostal;
	}

	@OneToMany(mappedBy = "ville")
	public Set<Abonne> getAbonnes() {
		return this.abonnes;
	}

	public void setAbonnes(Set<Abonne> abonnes) {
		this.abonnes = abonnes;
	}

}
