/********************************************************************************************************************
* VILLE
********************************************************************************************************************/

INSERT INTO itinelib.ville (NOMVILLE, CODEPOSTAL) VALUE ('Paris', '75000');
INSERT INTO itinelib.ville (NOMVILLE, CODEPOSTAL) VALUE ('Saint-Cloud','92210');
INSERT INTO itinelib.ville (NOMVILLE, CODEPOSTAL) VALUE ('Malakoff', '92240');
INSERT INTO itinelib.ville (NOMVILLE, CODEPOSTAL) VALUE ('Vanves', '92170');
INSERT INTO itinelib.ville (NOMVILLE, CODEPOSTAL) VALUE ('Saint-Denis', '93210');
INSERT INTO itinelib.ville (NOMVILLE, CODEPOSTAL) VALUE ('Charenton', '94220');
INSERT INTO itinelib.ville (NOMVILLE, CODEPOSTAL) VALUE ('Boulogne Billancourt', '92100');
INSERT INTO itinelib.ville (NOMVILLE, CODEPOSTAL) VALUE ('Montreuil','93100');
INSERT INTO itinelib.ville (NOMVILLE, CODEPOSTAL) VALUE ('Creteil','94000');
INSERT INTO itinelib.ville (NOMVILLE, CODEPOSTAL) VALUE ('Colombes','92700');
INSERT INTO itinelib.ville (NOMVILLE, CODEPOSTAL) VALUE ('Courbevoie','92400');
INSERT INTO itinelib.ville (NOMVILLE, CODEPOSTAL) VALUE ('Aubervilliers','93300');
INSERT INTO itinelib.ville (NOMVILLE, CODEPOSTAL) VALUE ('Drancy','93700');
INSERT INTO itinelib.ville (NOMVILLE, CODEPOSTAL) VALUE ('Antony','92160');
INSERT INTO itinelib.ville (NOMVILLE, CODEPOSTAL) VALUE ('Clichy','92110');
INSERT INTO itinelib.ville (NOMVILLE, CODEPOSTAL) VALUE ('Levallois-Perret','92300');
INSERT INTO itinelib.ville (NOMVILLE, CODEPOSTAL) VALUE ('Maisons-Alfort','94700');
INSERT INTO itinelib.ville (NOMVILLE, CODEPOSTAL) VALUE ('Vitry-sur-Seine','94400');
INSERT INTO itinelib.ville (NOMVILLE, CODEPOSTAL) VALUE ('Aulnay-sous-Bois','93600');


SELECT * FROM ville v;

/********************************************************************************************************************
* ABONNE
********************************************************************************************************************/

INSERT INTO itinelib.abonne(IDVILLE, NOMABONNE, PRENOMABONNE, ADRESSE, TEL, DATENAISSANCE, SEXE, TITULAIRECOMPTE, CODEBANQUE, CODEAGENCE, NUMEROCOMPTE, CLEFRIB) VALUE ('1', 'Ricaud', 'Benoit', '23, rue Armengaud', '0622707963', '1982-09-25', 'M', 'Benoit Ricaud', '366', '18', '36654545454544554', '123');
INSERT INTO itinelib.abonne(IDVILLE, NOMABONNE, PRENOMABONNE, ADRESSE, TEL, DATENAISSANCE, SEXE, TITULAIRECOMPTE, CODEBANQUE, CODEAGENCE, NUMEROCOMPTE, CLEFRIB) VALUE ('5','Patulacci','Robert','5 rue des bienfaiteurs','1-42-568-7558','1968-12-18','M','robert patulacci','325','00256','5830586463678629','65');
INSERT INTO itinelib.abonne(IDVILLE, NOMABONNE, PRENOMABONNE, ADRESSE, TEL, DATENAISSANCE, SEXE, TITULAIRECOMPTE, CODEBANQUE, CODEAGENCE, NUMEROCOMPTE, CLEFRIB) VALUE ('5','Watson','Sawyer','Ap #802-6255 Pede, Av.','1-966-967-259','1968-12-18','F','Jakeem Trevino','325','00256','5830586463678629','279');
INSERT INTO itinelib.abonne(IDVILLE, NOMABONNE, PRENOMABONNE, ADRESSE, TEL, DATENAISSANCE, SEXE, TITULAIRECOMPTE, CODEBANQUE, CODEAGENCE, NUMEROCOMPTE, CLEFRIB) VALUE ('4','Page','Mariam','149-5112 Neque Rd.','1-181-158-0155','1971-01-26','F','Amena Robertson','325','00256','5728697023354471','201');
INSERT INTO itinelib.abonne(IDVILLE, NOMABONNE, PRENOMABONNE, ADRESSE, TEL, DATENAISSANCE, SEXE, TITULAIRECOMPTE, CODEBANQUE, CODEAGENCE, NUMEROCOMPTE, CLEFRIB) VALUE ('14','Mann','Helen','P.O. Box 380, 9076 Ultricies Street','1-534-625-7737','1988-12-28','M','Hamilton Yang','325','00256','5390121588483453','184');
INSERT INTO itinelib.abonne(IDVILLE, NOMABONNE, PRENOMABONNE, ADRESSE, TEL, DATENAISSANCE, SEXE, TITULAIRECOMPTE, CODEBANQUE, CODEAGENCE, NUMEROCOMPTE, CLEFRIB) VALUE ('16','Burke','Ursa','410-9370 Convallis Ave','1-468-802-4272','1971-01-30','F','Brent Clemons','325','00256','5253774524200707','200');
INSERT INTO itinelib.abonne(IDVILLE, NOMABONNE, PRENOMABONNE, ADRESSE, TEL, DATENAISSANCE, SEXE, TITULAIRECOMPTE, CODEBANQUE, CODEAGENCE, NUMEROCOMPTE, CLEFRIB) VALUE ('4','Morin','Unity','4187 Pede. Ave','1-417-454-2444','1974-07-02','F','Ayanna Howe','325','00256','5535696219652891','184');
INSERT INTO itinelib.abonne(IDVILLE, NOMABONNE, PRENOMABONNE, ADRESSE, TEL, DATENAISSANCE, SEXE, TITULAIRECOMPTE, CODEBANQUE, CODEAGENCE, NUMEROCOMPTE, CLEFRIB) VALUE ('12','Pena','Minerva','993-8408 Magna Avenue','1-182-500-8541','1993-09-18','M','Wayne Caldwell','325','00256','5302917653694749','107');
INSERT INTO itinelib.abonne(IDVILLE, NOMABONNE, PRENOMABONNE, ADRESSE, TEL, DATENAISSANCE, SEXE, TITULAIRECOMPTE, CODEBANQUE, CODEAGENCE, NUMEROCOMPTE, CLEFRIB) VALUE ('12','Shepard','Jael','P.O. Box 303, 4486 Mauris Rd.','1-522-505-0059','1989-08-16','M','Hedy Glover','325','00256','5538434498012066','169');
INSERT INTO itinelib.abonne(IDVILLE, NOMABONNE, PRENOMABONNE, ADRESSE, TEL, DATENAISSANCE, SEXE, TITULAIRECOMPTE, CODEBANQUE, CODEAGENCE, NUMEROCOMPTE, CLEFRIB) VALUE ('10','Sherman','Harding','2238 Diam. Ave','1-394-746-9974','1994-06-24','F','Alexandra Ware','325','00256','5831789770629257','239');
INSERT INTO itinelib.abonne(IDVILLE, NOMABONNE, PRENOMABONNE, ADRESSE, TEL, DATENAISSANCE, SEXE, TITULAIRECOMPTE, CODEBANQUE, CODEAGENCE, NUMEROCOMPTE, CLEFRIB) VALUE ('7','Clayton','Damian','P.O. Box 160, 7198 A Rd.','1-799-983-6206','1972-05-23','F','Christen Walker','325','00256','5161254822742194','144');
INSERT INTO itinelib.abonne(IDVILLE, NOMABONNE, PRENOMABONNE, ADRESSE, TEL, DATENAISSANCE, SEXE, TITULAIRECOMPTE, CODEBANQUE, CODEAGENCE, NUMEROCOMPTE, CLEFRIB) VALUE ('18','Wynn','Ulysses','P.O. Box 911, 8283 Eget St.','1-395-984-9786','1983-06-07','F','Kasimir Collier','325','00256','5538439521100372','243');
INSERT INTO itinelib.abonne(IDVILLE, NOMABONNE, PRENOMABONNE, ADRESSE, TEL, DATENAISSANCE, SEXE, TITULAIRECOMPTE, CODEBANQUE, CODEAGENCE, NUMEROCOMPTE, CLEFRIB) VALUE ('3','Page','Vincent','2229 Dui Ave','1-801-720-2297','1985-01-30','F','Berk Armstrong','325','00256','5098937618080526','196');
INSERT INTO itinelib.abonne(IDVILLE, NOMABONNE, PRENOMABONNE, ADRESSE, TEL, DATENAISSANCE, SEXE, TITULAIRECOMPTE, CODEBANQUE, CODEAGENCE, NUMEROCOMPTE, CLEFRIB) VALUE ('11','Finley','Aladdin','Ap #271-4147 Placerat, Road','1-406-307-9281','1986-05-10','F','Kitra Dean','325','00256','5925661008339376','231');
INSERT INTO itinelib.abonne(IDVILLE, NOMABONNE, PRENOMABONNE, ADRESSE, TEL, DATENAISSANCE, SEXE, TITULAIRECOMPTE, CODEBANQUE, CODEAGENCE, NUMEROCOMPTE, CLEFRIB) VALUE ('5','Avery','Buckminster','P.O. Box 132, 7246 Amet, Street','1-821-327-5345','1979-09-04','M','Sybil Mcfadden','325','00256','5114571726415306','187');
INSERT INTO itinelib.abonne(IDVILLE, NOMABONNE, PRENOMABONNE, ADRESSE, TEL, DATENAISSANCE, SEXE, TITULAIRECOMPTE, CODEBANQUE, CODEAGENCE, NUMEROCOMPTE, CLEFRIB) VALUE ('17','Barr','Basia','P.O. Box 867, 3831 Ac St.','1-480-312-5391','1966-06-04','F','Keane Tran','325','00256','5022934383712708','181');
INSERT INTO itinelib.abonne(IDVILLE, NOMABONNE, PRENOMABONNE, ADRESSE, TEL, DATENAISSANCE, SEXE, TITULAIRECOMPTE, CODEBANQUE, CODEAGENCE, NUMEROCOMPTE, CLEFRIB) VALUE ('10','Campbell','Serina','3919 Eget, St.','1-312-651-7829','1992-09-04','F','Brody Poole','325','00256','5211688845418393','203');
INSERT INTO itinelib.abonne(IDVILLE, NOMABONNE, PRENOMABONNE, ADRESSE, TEL, DATENAISSANCE, SEXE, TITULAIRECOMPTE, CODEBANQUE, CODEAGENCE, NUMEROCOMPTE, CLEFRIB) VALUE ('6','Burch','Kelsey','Ap #556-9307 Fringilla Rd.','1-843-165-7164','1979-05-19','F','Riley Velazquez','325','00256','5722698383964598','288');
INSERT INTO itinelib.abonne(IDVILLE, NOMABONNE, PRENOMABONNE, ADRESSE, TEL, DATENAISSANCE, SEXE, TITULAIRECOMPTE, CODEBANQUE, CODEAGENCE, NUMEROCOMPTE, CLEFRIB) VALUE ('14','Wall','Ivor','5849 At St.','1-660-655-9614','1987-11-03','F','Brian Massey','325','00256','5628140764310956','187');
INSERT INTO itinelib.abonne(IDVILLE, NOMABONNE, PRENOMABONNE, ADRESSE, TEL, DATENAISSANCE, SEXE, TITULAIRECOMPTE, CODEBANQUE, CODEAGENCE, NUMEROCOMPTE, CLEFRIB) VALUE ('8','Mack','Candace','P.O. Box 782, 1370 Non, St.','1-277-837-3933','1969-05-14','M','Lacy Wood','325','00256','5981061261612922','238');
INSERT INTO itinelib.abonne(IDVILLE, NOMABONNE, PRENOMABONNE, ADRESSE, TEL, DATENAISSANCE, SEXE, TITULAIRECOMPTE, CODEBANQUE, CODEAGENCE, NUMEROCOMPTE, CLEFRIB) VALUE ('12','Mcneil','Briar','313-3818 Mi, St.','1-495-572-3107','1975-01-19','M','Halla Lindsay','325','00256','5711867673322559','289');
INSERT INTO itinelib.abonne(IDVILLE, NOMABONNE, PRENOMABONNE, ADRESSE, TEL, DATENAISSANCE, SEXE, TITULAIRECOMPTE, CODEBANQUE, CODEAGENCE, NUMEROCOMPTE, CLEFRIB) VALUE ('11','Osborn','Mallory','120 Nisi Street','1-502-842-3995','1974-11-10','M','Adria Patton','325','00256','5697614687960595','262');
INSERT INTO itinelib.abonne(IDVILLE, NOMABONNE, PRENOMABONNE, ADRESSE, TEL, DATENAISSANCE, SEXE, TITULAIRECOMPTE, CODEBANQUE, CODEAGENCE, NUMEROCOMPTE, CLEFRIB) VALUE ('2','Delacruz','Katelyn','P.O. Box 697, 8298 Urna. Ave','1-548-940-8831','1962-01-24','F','Arsenio Lowe','325','00256','5198339619208127','115');
INSERT INTO itinelib.abonne(IDVILLE, NOMABONNE, PRENOMABONNE, ADRESSE, TEL, DATENAISSANCE, SEXE, TITULAIRECOMPTE, CODEBANQUE, CODEAGENCE, NUMEROCOMPTE, CLEFRIB) VALUE ('6','Terrell','Tamara','435-8833 Dui, St.','1-607-245-1969','1972-08-24','M','Oliver Mccarthy','325','00256','5138121129479259','259');
INSERT INTO itinelib.abonne(IDVILLE, NOMABONNE, PRENOMABONNE, ADRESSE, TEL, DATENAISSANCE, SEXE, TITULAIRECOMPTE, CODEBANQUE, CODEAGENCE, NUMEROCOMPTE, CLEFRIB) VALUE ('3','Gibson','Stella','7270 Ligula. Street','1-410-371-9954','1962-03-10','F','Britanney Winters','325','00256','5210754522588104','295');
INSERT INTO itinelib.abonne(IDVILLE, NOMABONNE, PRENOMABONNE, ADRESSE, TEL, DATENAISSANCE, SEXE, TITULAIRECOMPTE, CODEBANQUE, CODEAGENCE, NUMEROCOMPTE, CLEFRIB) VALUE ('15','Romero','Blossom','432-3066 Purus Avenue','1-710-131-2022','1981-04-06','M','Bo Patrick','325','00256','5853284388780594','147');
INSERT INTO itinelib.abonne(IDVILLE, NOMABONNE, PRENOMABONNE, ADRESSE, TEL, DATENAISSANCE, SEXE, TITULAIRECOMPTE, CODEBANQUE, CODEAGENCE, NUMEROCOMPTE, CLEFRIB) VALUE ('14','Benton','Coby','901-7756 Mauris Av.','1-720-430-4627','1960-07-17','M','Vanna Oneill','325','00255','5566599652636796','108');
INSERT INTO itinelib.abonne(IDVILLE, NOMABONNE, PRENOMABONNE, ADRESSE, TEL, DATENAISSANCE, SEXE, TITULAIRECOMPTE, CODEBANQUE, CODEAGENCE, NUMEROCOMPTE, CLEFRIB) VALUE ('8','Hickman','Dustin','530-3461 Enim Rd.','1-831-661-0024','1983-01-01','F','Gail Fischer','325','00235','5997940211556852','153');
INSERT INTO itinelib.abonne(IDVILLE, NOMABONNE, PRENOMABONNE, ADRESSE, TEL, DATENAISSANCE, SEXE, TITULAIRECOMPTE, CODEBANQUE, CODEAGENCE, NUMEROCOMPTE, CLEFRIB) VALUE ('2','Marshall','Eugenia','Ap #513-4736 Vivamus Avenue','1-198-839-4914','1963-05-11','F','Channing Solomon','325','00352','5502300153020769','204');
INSERT INTO itinelib.abonne(IDVILLE, NOMABONNE, PRENOMABONNE, ADRESSE, TEL, DATENAISSANCE, SEXE, TITULAIRECOMPTE, CODEBANQUE, CODEAGENCE, NUMEROCOMPTE, CLEFRIB) VALUE ('3','King','Raven','P.O. Box 549, 587 Sit St.','1-795-783-6220','1988-04-07','M','Quon Molina','325','00864','5771912592463196','291');
INSERT INTO itinelib.abonne(IDVILLE, NOMABONNE, PRENOMABONNE, ADRESSE, TEL, DATENAISSANCE, SEXE, TITULAIRECOMPTE, CODEBANQUE, CODEAGENCE, NUMEROCOMPTE, CLEFRIB) VALUE ('10','Evans','Jena','789-8408 Pede. Ave','1-428-124-7174','1989-08-01','F','Kuame Blackburn','325','00333','5604281147476286','166');
INSERT INTO itinelib.abonne(IDVILLE, NOMABONNE, PRENOMABONNE, ADRESSE, TEL, DATENAISSANCE, SEXE, TITULAIRECOMPTE, CODEBANQUE, CODEAGENCE, NUMEROCOMPTE, CLEFRIB) VALUE ('15','Haley','Echo','8387 Lorem Rd.','1-406-338-1305','1984-03-24','F','Barry Wynn','325','00286','5598422168754041','131');
INSERT INTO itinelib.abonne(IDVILLE, NOMABONNE, PRENOMABONNE, ADRESSE, TEL, DATENAISSANCE, SEXE, TITULAIRECOMPTE, CODEBANQUE, CODEAGENCE, NUMEROCOMPTE, CLEFRIB) VALUE ('12','Noble','Quail','P.O. Box 249, 5774 Ultricies Road','1-894-290-4386','1962-05-24','F','Jack Perez','325','00964','5747661713510752','208');
INSERT INTO itinelib.abonne(IDVILLE, NOMABONNE, PRENOMABONNE, ADRESSE, TEL, DATENAISSANCE, SEXE, TITULAIRECOMPTE, CODEBANQUE, CODEAGENCE, NUMEROCOMPTE, CLEFRIB) VALUE ('15','Goff','Nero','229-4002 Litora St.','1-639-423-6130','1965-02-28','M','Ali Hogan','325','00256','5388404888566583','196');
INSERT INTO itinelib.abonne(IDVILLE, NOMABONNE, PRENOMABONNE, ADRESSE, TEL, DATENAISSANCE, SEXE, TITULAIRECOMPTE, CODEBANQUE, CODEAGENCE, NUMEROCOMPTE, CLEFRIB) VALUE ('3','Cameron','Alana','Ap #208-5048 Sed Rd.','1-228-858-1827','1983-12-29','M','Lydia Carr','325','0063','5503807316999882','229');
INSERT INTO itinelib.abonne(IDVILLE, NOMABONNE, PRENOMABONNE, ADRESSE, TEL, DATENAISSANCE, SEXE, TITULAIRECOMPTE, CODEBANQUE, CODEAGENCE, NUMEROCOMPTE, CLEFRIB) VALUE ('12','Tanner','Brianna','P.O. Box 624, 5153 Vestibulum St.','1-870-199-8570','1970-12-11','M','Quyn Lindsey','325','00688','5288487982936203','177');
INSERT INTO itinelib.abonne(IDVILLE, NOMABONNE, PRENOMABONNE, ADRESSE, TEL, DATENAISSANCE, SEXE, TITULAIRECOMPTE, CODEBANQUE, CODEAGENCE, NUMEROCOMPTE, CLEFRIB) VALUE ('14','Rosa','Ali','P.O. Box 987, 7156 Ad Ave','1-352-222-2210','1961-11-23','M','Jacob Lopez','325','00458','5606804150156677','145');
INSERT INTO itinelib.abonne(IDVILLE, NOMABONNE, PRENOMABONNE, ADRESSE, TEL, DATENAISSANCE, SEXE, TITULAIRECOMPTE, CODEBANQUE, CODEAGENCE, NUMEROCOMPTE, CLEFRIB) VALUE ('2','Terrell','Luke','Ap #122-3783 Nunc Ave','1-800-153-2854','1972-03-26','M','Zeus Keller','325','00936','5580848537851125','190');
INSERT INTO itinelib.abonne(IDVILLE, NOMABONNE, PRENOMABONNE, ADRESSE, TEL, DATENAISSANCE, SEXE, TITULAIRECOMPTE, CODEBANQUE, CODEAGENCE, NUMEROCOMPTE, CLEFRIB) VALUE ('1','Coleman','Minerva','887-7728 Dictum. St.','1-991-792-8450','1967-06-01','F','Emma Giles','325','07528','5829518158920110','159');
INSERT INTO itinelib.abonne(IDVILLE, NOMABONNE, PRENOMABONNE, ADRESSE, TEL, DATENAISSANCE, SEXE, TITULAIRECOMPTE, CODEBANQUE, CODEAGENCE, NUMEROCOMPTE, CLEFRIB) VALUE ('17','Hensley','Patrick','976-6841 Magna, Rd.','1-784-675-3681','1964-04-17','M','Ursula Colon','325','00987','5029787369072437','145');
INSERT INTO itinelib.abonne(IDVILLE, NOMABONNE, PRENOMABONNE, ADRESSE, TEL, DATENAISSANCE, SEXE, TITULAIRECOMPTE, CODEBANQUE, CODEAGENCE, NUMEROCOMPTE, CLEFRIB) VALUE ('11','Solomon','Kato','298-8690 Felis Street','1-715-400-0753','1974-07-15','M','Benjamin Craft','325','00278','5706630030181259','104');
INSERT INTO itinelib.abonne(IDVILLE, NOMABONNE, PRENOMABONNE, ADRESSE, TEL, DATENAISSANCE, SEXE, TITULAIRECOMPTE, CODEBANQUE, CODEAGENCE, NUMEROCOMPTE, CLEFRIB) VALUE ('8','Powell','Deanna','2941 Ac Rd.','1-805-777-2172','1975-09-28','F','Bert Mcgee','325','00255','5065224259160459','289');

SELECT * FROM abonne a;


/********************************************************************************************************************
*EMPLOYE
********************************************************************************************************************/

INSERT INTO itinelib.employe (NOMEMPLOYE,PRENOMEMPLOYE,SERVICE) VALUE ('Ricaud','Benoit','informatique');
INSERT INTO itinelib.employe (NOMEMPLOYE,PRENOMEMPLOYE,SERVICE) VALUE('Champain','Romain','Commercial');
INSERT INTO itinelib.employe (NOMEMPLOYE,PRENOMEMPLOYE,SERVICE) VALUE('Delavaut','Romain','informatique');
INSERT INTO itinelib.employe (NOMEMPLOYE,PRENOMEMPLOYE,SERVICE) VALUE('Dufour','Claude','technique');
INSERT INTO itinelib.employe (NOMEMPLOYE,PRENOMEMPLOYE,SERVICE) VALUE('couture','Marie','Administration');



/******************************************************************************************************************
*CATEGORIEPERMIS
******************************************************************************************************************/
INSERT itinelib.categoriepermis(NOMPERMIS) VALUE ('B');

/******************************************************************************************************************
*UTILISATEUR
*******************************************************************************************************************/

INSERT INTO itinelib.utilisateur (IDABONNE,IDEMPLOYE,EMAIL,MOTDEPASS_HASH,MOTDEPASS_SALT,ROLE) VALUE ('1','1','benoitricaud@gmail.com', '123456', '123456', 'Administrateur');
INSERT INTO itinelib.utilisateur (IDABONNE,IDEMPLOYE,EMAIL,MOTDEPASS_HASH,MOTDEPASS_SALT,ROLE) VALUE ('2',null,'amet@gmail.com', 'azerty', 'azerty', 'User');
INSERT INTO itinelib.utilisateur (IDABONNE,IDEMPLOYE,EMAIL,MOTDEPASS_HASH,MOTDEPASS_SALT,ROLE) VALUE ('3',null,'dolor.sit.amet@eueuismodac.ca', 'azerty', 'azerty', 'User');
INSERT INTO itinelib.utilisateur (IDABONNE,IDEMPLOYE,EMAIL,MOTDEPASS_HASH,MOTDEPASS_SALT,ROLE) VALUE ('4',null,'tempor.diam@metusIn.ca', 'azerty', 'azerty', 'User');
INSERT INTO itinelib.utilisateur (IDABONNE,IDEMPLOYE,EMAIL,MOTDEPASS_HASH,MOTDEPASS_SALT,ROLE) VALUE ('5',null,'ipsum.Suspendisse.non@tinciduntadipiscing.edu', 'azerty', 'azerty', 'User');
INSERT INTO itinelib.utilisateur (IDABONNE,IDEMPLOYE,EMAIL,MOTDEPASS_HASH,MOTDEPASS_SALT,ROLE) VALUE ('6',null,'sagittis.Duis@Donecelementumlorem.edu', 'azerty', 'azerty', 'User');
INSERT INTO itinelib.utilisateur (IDABONNE,IDEMPLOYE,EMAIL,MOTDEPASS_HASH,MOTDEPASS_SALT,ROLE) VALUE ('7',null,'sed.pede.nec@mollis.org', 'azerty', 'azerty', 'User');
INSERT INTO itinelib.utilisateur (IDABONNE,IDEMPLOYE,EMAIL,MOTDEPASS_HASH,MOTDEPASS_SALT,ROLE) VALUE ('8',null,'sed.sem.egestas@nonquam.org', 'azerty', 'azerty', 'User');
INSERT INTO itinelib.utilisateur (IDABONNE,IDEMPLOYE,EMAIL,MOTDEPASS_HASH,MOTDEPASS_SALT,ROLE) VALUE ('9',null,'Proin.mi@turpis.ca', 'azerty', 'azerty', 'User');
INSERT INTO itinelib.utilisateur (IDABONNE,IDEMPLOYE,EMAIL,MOTDEPASS_HASH,MOTDEPASS_SALT,ROLE) VALUE ('10',null,'adipiscing@eu.com', 'azerty', 'azerty', 'User');
INSERT INTO itinelib.utilisateur (IDABONNE,IDEMPLOYE,EMAIL,MOTDEPASS_HASH,MOTDEPASS_SALT,ROLE) VALUE ('11',null,'Suspendisse@Proin.org', 'azerty', 'azerty', 'User');
INSERT INTO itinelib.utilisateur (IDABONNE,IDEMPLOYE,EMAIL,MOTDEPASS_HASH,MOTDEPASS_SALT,ROLE) VALUE ('12',null,'Quisque@tempus.org', 'azerty', 'azerty', 'User');
INSERT INTO itinelib.utilisateur (IDABONNE,IDEMPLOYE,EMAIL,MOTDEPASS_HASH,MOTDEPASS_SALT,ROLE) VALUE ('13',null,'consectetuer@Donecelementum.org', 'azerty', 'azerty', 'User');
INSERT INTO itinelib.utilisateur (IDABONNE,IDEMPLOYE,EMAIL,MOTDEPASS_HASH,MOTDEPASS_SALT,ROLE) VALUE ('14',null,'dolor.sit@Intinciduntcongue.com', 'azerty', 'azerty', 'User');
INSERT INTO itinelib.utilisateur (IDABONNE,IDEMPLOYE,EMAIL,MOTDEPASS_HASH,MOTDEPASS_SALT,ROLE) VALUE ('15',null,'adipiscing.ligula@sagittisDuisgravida.edu', 'azerty', 'azerty', 'User');
INSERT INTO itinelib.utilisateur (IDABONNE,IDEMPLOYE,EMAIL,MOTDEPASS_HASH,MOTDEPASS_SALT,ROLE) VALUE ('16',null,'orci.Ut.sagittis@loremauctor.ca', 'azerty', 'azerty', 'User');
INSERT INTO itinelib.utilisateur (IDABONNE,IDEMPLOYE,EMAIL,MOTDEPASS_HASH,MOTDEPASS_SALT,ROLE) VALUE ('17',null,'dolor.dolor@sagittislobortismauris.com', 'azerty', 'azerty', 'User');
INSERT INTO itinelib.utilisateur (IDABONNE,IDEMPLOYE,EMAIL,MOTDEPASS_HASH,MOTDEPASS_SALT,ROLE) VALUE ('18',null,'nunc.ac.mattis@sedpede.org', 'azerty', 'azerty', 'User');
INSERT INTO itinelib.utilisateur (IDABONNE,IDEMPLOYE,EMAIL,MOTDEPASS_HASH,MOTDEPASS_SALT,ROLE) VALUE ('19',null,'Morbi@egestas.edu', 'azerty', 'azerty', 'User');
INSERT INTO itinelib.utilisateur (IDABONNE,IDEMPLOYE,EMAIL,MOTDEPASS_HASH,MOTDEPASS_SALT,ROLE) VALUE ('20',null,'purus.Duis@mieleifendegestas.org', 'azerty', 'azerty', 'User');
INSERT INTO itinelib.utilisateur (IDABONNE,IDEMPLOYE,EMAIL,MOTDEPASS_HASH,MOTDEPASS_SALT,ROLE) VALUE ('21',null,'odio@blandit.ca', 'azerty', 'azerty', 'User');
INSERT INTO itinelib.utilisateur (IDABONNE,IDEMPLOYE,EMAIL,MOTDEPASS_HASH,MOTDEPASS_SALT,ROLE) VALUE ('22',null,'Cras@neceuismod.edu', 'azerty', 'azerty', 'User');
INSERT INTO itinelib.utilisateur (IDABONNE,IDEMPLOYE,EMAIL,MOTDEPASS_HASH,MOTDEPASS_SALT,ROLE) VALUE ('23',null,'tempus.risus.Donec@Naminterdumenim.com', 'azerty', 'azerty', 'User');
INSERT INTO itinelib.utilisateur (IDABONNE,IDEMPLOYE,EMAIL,MOTDEPASS_HASH,MOTDEPASS_SALT,ROLE) VALUE ('24',null,'nunc.Quisque.ornare@pede.edu', 'azerty', 'azerty', 'User');
INSERT INTO itinelib.utilisateur (IDABONNE,IDEMPLOYE,EMAIL,MOTDEPASS_HASH,MOTDEPASS_SALT,ROLE) VALUE ('25',null,'ridiculus@urna.com', 'azerty', 'azerty', 'User');
INSERT INTO itinelib.utilisateur (IDABONNE,IDEMPLOYE,EMAIL,MOTDEPASS_HASH,MOTDEPASS_SALT,ROLE) VALUE ('26',null,'tristique@egestasAliquamnec.com', 'azerty', 'azerty', 'User');
INSERT INTO itinelib.utilisateur (IDABONNE,IDEMPLOYE,EMAIL,MOTDEPASS_HASH,MOTDEPASS_SALT,ROLE) VALUE ('27',null,'enim.nec.tempus@elit.com', 'azerty', 'azerty', 'User');
INSERT INTO itinelib.utilisateur (IDABONNE,IDEMPLOYE,EMAIL,MOTDEPASS_HASH,MOTDEPASS_SALT,ROLE) VALUE ('28',null,'ac.tellus.Suspendisse@amet.ca', 'azerty', 'azerty', 'User');
INSERT INTO itinelib.utilisateur (IDABONNE,IDEMPLOYE,EMAIL,MOTDEPASS_HASH,MOTDEPASS_SALT,ROLE) VALUE ('29',null,'neque.Nullam.nisl@quamCurabiturvel.ca', 'azerty', 'azerty', 'User');
INSERT INTO itinelib.utilisateur (IDABONNE,IDEMPLOYE,EMAIL,MOTDEPASS_HASH,MOTDEPASS_SALT,ROLE) VALUE ('30',null,'ac@sitamet.org', 'azerty', 'azerty', 'User');
INSERT INTO itinelib.utilisateur (IDABONNE,IDEMPLOYE,EMAIL,MOTDEPASS_HASH,MOTDEPASS_SALT,ROLE) VALUE ('31',null,'euismod@hendrerit.org', 'azerty', 'azerty', 'User');
INSERT INTO itinelib.utilisateur (IDABONNE,IDEMPLOYE,EMAIL,MOTDEPASS_HASH,MOTDEPASS_SALT,ROLE) VALUE ('32',null,'risus.odio.auctor@cursus.edu', 'azerty', 'azerty', 'User');
INSERT INTO itinelib.utilisateur (IDABONNE,IDEMPLOYE,EMAIL,MOTDEPASS_HASH,MOTDEPASS_SALT,ROLE) VALUE ('33',null,'imperdiet.ornare@molestiesodalesMauris.edu', 'azerty', 'azerty', 'User');
INSERT INTO itinelib.utilisateur (IDABONNE,IDEMPLOYE,EMAIL,MOTDEPASS_HASH,MOTDEPASS_SALT,ROLE) VALUE ('34',null,'vel.faucibus.id@sitametfaucibus.ca', 'azerty', 'azerty', 'User');
INSERT INTO itinelib.utilisateur (IDABONNE,IDEMPLOYE,EMAIL,MOTDEPASS_HASH,MOTDEPASS_SALT,ROLE) VALUE ('35',null,'elit.Curabitur@pedeCumsociis.org', 'azerty', 'azerty', 'User');
INSERT INTO itinelib.utilisateur (IDABONNE,IDEMPLOYE,EMAIL,MOTDEPASS_HASH,MOTDEPASS_SALT,ROLE) VALUE ('36',null,'luctus.vulputate.nisi@ante.ca', 'azerty', 'azerty', 'User');
INSERT INTO itinelib.utilisateur (IDABONNE,IDEMPLOYE,EMAIL,MOTDEPASS_HASH,MOTDEPASS_SALT,ROLE) VALUE ('37',null,'magnis@ultricesDuis.org', 'azerty', 'azerty', 'User');
INSERT INTO itinelib.utilisateur (IDABONNE,IDEMPLOYE,EMAIL,MOTDEPASS_HASH,MOTDEPASS_SALT,ROLE) VALUE ('38',null,'odio.semper@dictumeleifend.ca', 'azerty', 'azerty', 'User');
INSERT INTO itinelib.utilisateur (IDABONNE,IDEMPLOYE,EMAIL,MOTDEPASS_HASH,MOTDEPASS_SALT,ROLE) VALUE ('39',null,'Nullam@lectus.com', 'azerty', 'azerty', 'User');
INSERT INTO itinelib.utilisateur (IDABONNE,IDEMPLOYE,EMAIL,MOTDEPASS_HASH,MOTDEPASS_SALT,ROLE) VALUE ('40',null,'vehicula.aliquet@inlobortis.ca', 'azerty', 'azerty', 'User');
INSERT INTO itinelib.utilisateur (IDABONNE,IDEMPLOYE,EMAIL,MOTDEPASS_HASH,MOTDEPASS_SALT,ROLE) VALUE ('41',null,'Nullam@dictumultriciesligula.ca', 'azerty', 'azerty', 'User');
INSERT INTO itinelib.utilisateur (IDABONNE,IDEMPLOYE,EMAIL,MOTDEPASS_HASH,MOTDEPASS_SALT,ROLE) VALUE (null,'2','romchap@gmail.com', '123456', '123456', 'Administrateur');
INSERT INTO itinelib.utilisateur (IDABONNE,IDEMPLOYE,EMAIL,MOTDEPASS_HASH,MOTDEPASS_SALT,ROLE) VALUE (null,'3','Atodete@htomail.com', '123456', '123456', 'Administrateur');
INSERT INTO itinelib.utilisateur (IDABONNE,IDEMPLOYE,EMAIL,MOTDEPASS_HASH,MOTDEPASS_SALT,ROLE) VALUE (null,'4','theOne@free.fr', '123456', '123456', 'Administrateur');
INSERT INTO itinelib.utilisateur (IDABONNE,IDEMPLOYE,EMAIL,MOTDEPASS_HASH,MOTDEPASS_SALT,ROLE) VALUE (null,'5','titecourge@gmail.com', '123456', '123456', 'Administrateur');

/*****************************************************************************************
*DETENIR
******************************************************************************************/

INSERT INTO itinelib.detenir (IDABONNE,IDCATEGORIEPERMIS) VALUE ('1','1');
INSERT INTO itinelib.detenir (IDABONNE,IDCATEGORIEPERMIS) VALUE ('2','1');
INSERT INTO itinelib.detenir (IDABONNE,IDCATEGORIEPERMIS) VALUE ('5','1');
INSERT INTO itinelib.detenir (IDABONNE,IDCATEGORIEPERMIS) VALUE ('7','1');
INSERT INTO itinelib.detenir (IDABONNE,IDCATEGORIEPERMIS) VALUE ('9','1');
INSERT INTO itinelib.detenir (IDABONNE,IDCATEGORIEPERMIS) VALUE ('10','1');
INSERT INTO itinelib.detenir (IDABONNE,IDCATEGORIEPERMIS) VALUE ('11','1');
INSERT INTO itinelib.detenir (IDABONNE,IDCATEGORIEPERMIS) VALUE ('18','1');
INSERT INTO itinelib.detenir (IDABONNE,IDCATEGORIEPERMIS) VALUE ('19','1');
INSERT INTO itinelib.detenir (IDABONNE,IDCATEGORIEPERMIS) VALUE ('21','1');
INSERT INTO itinelib.detenir (IDABONNE,IDCATEGORIEPERMIS) VALUE ('24','1');
INSERT INTO itinelib.detenir (IDABONNE,IDCATEGORIEPERMIS) VALUE ('26','1');
INSERT INTO itinelib.detenir (IDABONNE,IDCATEGORIEPERMIS) VALUE ('27','1');
INSERT INTO itinelib.detenir (IDABONNE,IDCATEGORIEPERMIS) VALUE ('29','1');
INSERT INTO itinelib.detenir (IDABONNE,IDCATEGORIEPERMIS) VALUE ('30','1');
INSERT INTO itinelib.detenir (IDABONNE,IDCATEGORIEPERMIS) VALUE ('31','1');
INSERT INTO itinelib.detenir (IDABONNE,IDCATEGORIEPERMIS) VALUE ('33','1');
INSERT INTO itinelib.detenir (IDABONNE,IDCATEGORIEPERMIS) VALUE ('34','1');
INSERT INTO itinelib.detenir (IDABONNE,IDCATEGORIEPERMIS) VALUE ('36','1');
INSERT INTO itinelib.detenir (IDABONNE,IDCATEGORIEPERMIS) VALUE ('37','1');
INSERT INTO itinelib.detenir (IDABONNE,IDCATEGORIEPERMIS) VALUE ('39','1');
INSERT INTO itinelib.detenir (IDABONNE,IDCATEGORIEPERMIS) VALUE ('40','1');
INSERT INTO itinelib.detenir (IDABONNE,IDCATEGORIEPERMIS) VALUE ('41','1');

/*****************************************************************************************
*TYPEABONNEMENT
******************************************************************************************/

INSERT INTO itinelib.typeabonnement (NOMABONNEMENT,COUT) VALUE ('Velo','5');
INSERT INTO itinelib.typeabonnement (NOMABONNEMENT,COUT) VALUE ('Auto','9');
INSERT INTO itinelib.typeabonnement (NOMABONNEMENT,COUT) VALUE ('Auto & Velo','14');

/******************************************************************************************
*ABONNEMENT
********************************************************************************************/

INSERT INTO itinelib.abonnement (IDTYPE,IDABONNE,DHSOUSCRIPTION,DHRESILIATION) VALUE ('1','1','03/01/12',NULL);
INSERT INTO itinelib.abonnement (IDTYPE,IDABONNE,DHSOUSCRIPTION,DHRESILIATION) VALUE ('3','2','07/01/12',NULL);
INSERT INTO itinelib.abonnement (IDTYPE,IDABONNE,DHSOUSCRIPTION,DHRESILIATION) VALUE ('3','3','11/01/12',NULL);
INSERT INTO itinelib.abonnement (IDTYPE,IDABONNE,DHSOUSCRIPTION,DHRESILIATION) VALUE ('1','4','15/01/12',NULL);
INSERT INTO itinelib.abonnement (IDTYPE,IDABONNE,DHSOUSCRIPTION,DHRESILIATION) VALUE ('3','5','17/01/12',NULL);
INSERT INTO itinelib.abonnement (IDTYPE,IDABONNE,DHSOUSCRIPTION,DHRESILIATION) VALUE ('1','6','20/01/12','23/04/12');
INSERT INTO itinelib.abonnement (IDTYPE,IDABONNE,DHSOUSCRIPTION,DHRESILIATION) VALUE ('3','7','22/01/12',NULL);
INSERT INTO itinelib.abonnement (IDTYPE,IDABONNE,DHSOUSCRIPTION,DHRESILIATION) VALUE ('1','8','23/01/12','09/04/12');
INSERT INTO itinelib.abonnement (IDTYPE,IDABONNE,DHSOUSCRIPTION,DHRESILIATION) VALUE ('3','9','26/01/12',NULL);
INSERT INTO itinelib.abonnement (IDTYPE,IDABONNE,DHSOUSCRIPTION,DHRESILIATION) VALUE ('2','10','01/02/12',NULL);
INSERT INTO itinelib.abonnement (IDTYPE,IDABONNE,DHSOUSCRIPTION,DHRESILIATION) VALUE ('3','11','01/02/12',NULL);
INSERT INTO itinelib.abonnement (IDTYPE,IDABONNE,DHSOUSCRIPTION,DHRESILIATION) VALUE ('3','12','06/02/12',NULL);
INSERT INTO itinelib.abonnement (IDTYPE,IDABONNE,DHSOUSCRIPTION,DHRESILIATION) VALUE ('1','13','15/02/12',NULL);
INSERT INTO itinelib.abonnement (IDTYPE,IDABONNE,DHSOUSCRIPTION,DHRESILIATION) VALUE ('3','14','17/02/12',NULL);
INSERT INTO itinelib.abonnement (IDTYPE,IDABONNE,DHSOUSCRIPTION,DHRESILIATION) VALUE ('1','15','21/02/12',NULL);
INSERT INTO itinelib.abonnement (IDTYPE,IDABONNE,DHSOUSCRIPTION,DHRESILIATION) VALUE ('3','16','22/02/12',NULL);
INSERT INTO itinelib.abonnement (IDTYPE,IDABONNE,DHSOUSCRIPTION,DHRESILIATION) VALUE ('3','17','25/02/12',NULL);
INSERT INTO itinelib.abonnement (IDTYPE,IDABONNE,DHSOUSCRIPTION,DHRESILIATION) VALUE ('2','18','02/03/12',NULL);
INSERT INTO itinelib.abonnement (IDTYPE,IDABONNE,DHSOUSCRIPTION,DHRESILIATION) VALUE ('3','19','03/03/12',NULL);
INSERT INTO itinelib.abonnement (IDTYPE,IDABONNE,DHSOUSCRIPTION,DHRESILIATION) VALUE ('2','20','06/03/12',NULL);
INSERT INTO itinelib.abonnement (IDTYPE,IDABONNE,DHSOUSCRIPTION,DHRESILIATION) VALUE ('3','21','09/03/12',NULL);
INSERT INTO itinelib.abonnement (IDTYPE,IDABONNE,DHSOUSCRIPTION,DHRESILIATION) VALUE ('3','22','11/03/12',NULL);
INSERT INTO itinelib.abonnement (IDTYPE,IDABONNE,DHSOUSCRIPTION,DHRESILIATION) VALUE ('3','23','14/03/12',NULL);
INSERT INTO itinelib.abonnement (IDTYPE,IDABONNE,DHSOUSCRIPTION,DHRESILIATION) VALUE ('2','24','19/03/12',NULL);
INSERT INTO itinelib.abonnement (IDTYPE,IDABONNE,DHSOUSCRIPTION,DHRESILIATION) VALUE ('1','25','20/03/12',NULL);
INSERT INTO itinelib.abonnement (IDTYPE,IDABONNE,DHSOUSCRIPTION,DHRESILIATION) VALUE ('1','26','24/03/12',NULL);
INSERT INTO itinelib.abonnement (IDTYPE,IDABONNE,DHSOUSCRIPTION,DHRESILIATION) VALUE ('3','27','01/04/12','03/03/11');
INSERT INTO itinelib.abonnement (IDTYPE,IDABONNE,DHSOUSCRIPTION,DHRESILIATION) VALUE ('3','28','02/04/12',NULL);
INSERT INTO itinelib.abonnement (IDTYPE,IDABONNE,DHSOUSCRIPTION,DHRESILIATION) VALUE ('3','28','03/04/12',NULL);
INSERT INTO itinelib.abonnement (IDTYPE,IDABONNE,DHSOUSCRIPTION,DHRESILIATION) VALUE ('1','30','06/04/12','15/07/11');
INSERT INTO itinelib.abonnement (IDTYPE,IDABONNE,DHSOUSCRIPTION,DHRESILIATION) VALUE ('2','31','07/04/12',NULL);
INSERT INTO itinelib.abonnement (IDTYPE,IDABONNE,DHSOUSCRIPTION,DHRESILIATION) VALUE ('3','32','10/04/12',NULL);
INSERT INTO itinelib.abonnement (IDTYPE,IDABONNE,DHSOUSCRIPTION,DHRESILIATION) VALUE ('1','33','10/04/12',NULL);
INSERT INTO itinelib.abonnement (IDTYPE,IDABONNE,DHSOUSCRIPTION,DHRESILIATION) VALUE ('3','34','14/04/12',NULL);
INSERT INTO itinelib.abonnement (IDTYPE,IDABONNE,DHSOUSCRIPTION,DHRESILIATION) VALUE ('3','35','14/04/12','13/12/10');
INSERT INTO itinelib.abonnement (IDTYPE,IDABONNE,DHSOUSCRIPTION,DHRESILIATION) VALUE ('3','36','16/04/12',NULL);
INSERT INTO itinelib.abonnement (IDTYPE,IDABONNE,DHSOUSCRIPTION,DHRESILIATION) VALUE ('2','37','20/04/12',NULL);
INSERT INTO itinelib.abonnement (IDTYPE,IDABONNE,DHSOUSCRIPTION,DHRESILIATION) VALUE ('3','38','21/04/12',NULL);
INSERT INTO itinelib.abonnement (IDTYPE,IDABONNE,DHSOUSCRIPTION,DHRESILIATION) VALUE ('1','39','23/04/12',NULL);
INSERT INTO itinelib.abonnement (IDTYPE,IDABONNE,DHSOUSCRIPTION,DHRESILIATION) VALUE ('3','40','24/04/12',NULL);
INSERT INTO itinelib.abonnement (IDTYPE,IDABONNE,DHSOUSCRIPTION,DHRESILIATION) VALUE ('1','41','02/05/12',NULL);

/***********************************************************************************************
*POINTLOCATION
************************************************************************************************/

INSERT INTO itinelib.pointlocation (NOMPOINTLOCATION,LATTITUDE,LONGITUDE) VALUE ('Montparnasse - Velo','48.8380556','2.3269444');
INSERT INTO itinelib.pointlocation (NOMPOINTLOCATION,LATTITUDE,LONGITUDE) VALUE ('Montparnasse - Auto','48.8380556','2.3269444');
INSERT INTO itinelib.pointlocation (NOMPOINTLOCATION,LATTITUDE,LONGITUDE) VALUE ('Nation - Velo','48.848394','2.39591');
INSERT INTO itinelib.pointlocation (NOMPOINTLOCATION,LATTITUDE,LONGITUDE) VALUE ('Nation - Auto','48.848394','2.39591');
INSERT INTO itinelib.pointlocation (NOMPOINTLOCATION,LATTITUDE,LONGITUDE) VALUE ('Bastille - Velo','48.853082','2.369002');
INSERT INTO itinelib.pointlocation (NOMPOINTLOCATION,LATTITUDE,LONGITUDE) VALUE ('Bastille - Auto','48.853082','2.369002');
INSERT INTO itinelib.pointlocation (NOMPOINTLOCATION,LATTITUDE,LONGITUDE) VALUE ('Republique - Velo','48.867503','2.363811');
INSERT INTO itinelib.pointlocation (NOMPOINTLOCATION,LATTITUDE,LONGITUDE) VALUE ('Republique - Auto','48.867503','2.363811');
INSERT INTO itinelib.pointlocation (NOMPOINTLOCATION,LATTITUDE,LONGITUDE) VALUE ('CDG - Velo','48.8769501','2.2959324');
INSERT INTO itinelib.pointlocation (NOMPOINTLOCATION,LATTITUDE,LONGITUDE) VALUE ('CDG - Auto','48.8769501','2.2959324');
INSERT INTO itinelib.pointlocation (NOMPOINTLOCATION,LATTITUDE,LONGITUDE) VALUE ('Opera - Velo','48.87053','2.332535');
INSERT INTO itinelib.pointlocation (NOMPOINTLOCATION,LATTITUDE,LONGITUDE) VALUE ('Opera - Auto','48.87053','2.332535');
INSERT INTO itinelib.pointlocation (NOMPOINTLOCATION,LATTITUDE,LONGITUDE) VALUE ('Alesia - Velo','48.8284438','2.3250369');
INSERT INTO itinelib.pointlocation (NOMPOINTLOCATION,LATTITUDE,LONGITUDE) VALUE ('Alesia - Auto','48.8284438','2.3250369');
INSERT INTO itinelib.pointlocation (NOMPOINTLOCATION,LATTITUDE,LONGITUDE) VALUE ('SaintLazare - Velo','48.875496','2.326671');
INSERT INTO itinelib.pointlocation (NOMPOINTLOCATION,LATTITUDE,LONGITUDE) VALUE ('SaintLazare - Auto','48.875496','2.326671');
INSERT INTO itinelib.pointlocation (NOMPOINTLOCATION,LATTITUDE,LONGITUDE) VALUE ('Chatelet - Velo','48.858706','2.347456');
INSERT INTO itinelib.pointlocation (NOMPOINTLOCATION,LATTITUDE,LONGITUDE) VALUE ('Chatelet - Auto','48.858706','2.347456');
INSERT INTO itinelib.pointlocation (NOMPOINTLOCATION,LATTITUDE,LONGITUDE) VALUE ('GareDuNord - Velo','48.87977','2.355752');
INSERT INTO itinelib.pointlocation (NOMPOINTLOCATION,LATTITUDE,LONGITUDE) VALUE ('GareDuNord - Auto','48.87977','2.355752');
INSERT INTO itinelib.pointlocation (NOMPOINTLOCATION,LATTITUDE,LONGITUDE) VALUE ('SaintMichel - Velo','48.853387','2.343706');
INSERT INTO itinelib.pointlocation (NOMPOINTLOCATION,LATTITUDE,LONGITUDE) VALUE ('SaintMichel - Auto','48.853387','2.343706');
INSERT INTO itinelib.pointlocation (NOMPOINTLOCATION,LATTITUDE,LONGITUDE) VALUE ('Trocadero - Velo','48.8628733','2.2877526');
INSERT INTO itinelib.pointlocation (NOMPOINTLOCATION,LATTITUDE,LONGITUDE) VALUE ('Trocadero - Auto','48.8628733','2.2877526');
INSERT INTO itinelib.pointlocation (NOMPOINTLOCATION,LATTITUDE,LONGITUDE) VALUE ('PlaceDItalie - Velo','48.8317878','2.3559109');
INSERT INTO itinelib.pointlocation (NOMPOINTLOCATION,LATTITUDE,LONGITUDE) VALUE ('PlaceDItalie - Auto','48.8317878','2.3559109');
INSERT INTO itinelib.pointlocation (NOMPOINTLOCATION,LATTITUDE,LONGITUDE) VALUE ('GareDeLyon - Velo','48.8447174','2.3739303');
INSERT INTO itinelib.pointlocation (NOMPOINTLOCATION,LATTITUDE,LONGITUDE) VALUE ('GareDeLyon - Auto','48.8447174','2.3739303');
INSERT INTO itinelib.pointlocation (NOMPOINTLOCATION,LATTITUDE,LONGITUDE) VALUE ('PereLachaise - Velo','48.8613254','2.3942543');
INSERT INTO itinelib.pointlocation (NOMPOINTLOCATION,LATTITUDE,LONGITUDE) VALUE ('PereLachaise - Auto','48.8613254','2.3942543');
INSERT INTO itinelib.pointlocation (NOMPOINTLOCATION,LATTITUDE,LONGITUDE) VALUE ('PlaceDeClichy - Velo','48.883469','2.3268295');
INSERT INTO itinelib.pointlocation (NOMPOINTLOCATION,LATTITUDE,LONGITUDE) VALUE ('PlaceDeClichy - Auto','48.883469','2.3268295');
INSERT INTO itinelib.pointlocation (NOMPOINTLOCATION,LATTITUDE,LONGITUDE) VALUE ('Pigalle - Velo','48.882255','2.337573');
INSERT INTO itinelib.pointlocation (NOMPOINTLOCATION,LATTITUDE,LONGITUDE) VALUE ('Pigalle - Auto','48.882255','2.337573');
INSERT INTO itinelib.pointlocation (NOMPOINTLOCATION,LATTITUDE,LONGITUDE) VALUE ('Invalides - Auto','48.8629644','2.3143387');
INSERT INTO itinelib.pointlocation (NOMPOINTLOCATION,LATTITUDE,LONGITUDE) VALUE ('Grenelle - Velo','48.849047','2.297916');
INSERT INTO itinelib.pointlocation (NOMPOINTLOCATION,LATTITUDE,LONGITUDE) VALUE ('Grenelle - Auto','48.849047','2.297916');
INSERT INTO itinelib.pointlocation (NOMPOINTLOCATION,LATTITUDE,LONGITUDE) VALUE ('LouisBlanc - Velo','48.881203','2.365158');
INSERT INTO itinelib.pointlocation (NOMPOINTLOCATION,LATTITUDE,LONGITUDE) VALUE ('LouisBlanc - Auto','48.881203','2.365158');

/**********************************************************************************************
*CATEGORIEVEHICULE
************************************************************************************************/

INSERT INTO itinelib.categorievehicule (IDCATEGORIEPERMIS,NOMTYPEVEHICULE,TAUXHORAIRE,TAUXKILOMETRIQUE) VALUE (null,'Velo','5',null);
INSERT INTO itinelib.categorievehicule (IDCATEGORIEPERMIS,NOMTYPEVEHICULE,TAUXHORAIRE,TAUXKILOMETRIQUE) VALUE ('1','Auto','20',null);

/**********************************************************************************************
*VEHICULE
***********************************************************************************************/

INSERT INTO itinelib.vehicule (IDCATEGORIEVEHICULE) VALUE ('1');
INSERT INTO itinelib.vehicule (IDCATEGORIEVEHICULE) VALUE ('1');
INSERT INTO itinelib.vehicule (IDCATEGORIEVEHICULE) VALUE ('1');
INSERT INTO itinelib.vehicule (IDCATEGORIEVEHICULE) VALUE ('1');
INSERT INTO itinelib.vehicule (IDCATEGORIEVEHICULE) VALUE ('1');
INSERT INTO itinelib.vehicule (IDCATEGORIEVEHICULE) VALUE ('1');
INSERT INTO itinelib.vehicule (IDCATEGORIEVEHICULE) VALUE ('1');
INSERT INTO itinelib.vehicule (IDCATEGORIEVEHICULE) VALUE ('1');
INSERT INTO itinelib.vehicule (IDCATEGORIEVEHICULE) VALUE ('1');
INSERT INTO itinelib.vehicule (IDCATEGORIEVEHICULE) VALUE ('1');
INSERT INTO itinelib.vehicule (IDCATEGORIEVEHICULE) VALUE ('1');
INSERT INTO itinelib.vehicule (IDCATEGORIEVEHICULE) VALUE ('1');
INSERT INTO itinelib.vehicule (IDCATEGORIEVEHICULE) VALUE ('1');
INSERT INTO itinelib.vehicule (IDCATEGORIEVEHICULE) VALUE ('1');
INSERT INTO itinelib.vehicule (IDCATEGORIEVEHICULE) VALUE ('1');
INSERT INTO itinelib.vehicule (IDCATEGORIEVEHICULE) VALUE ('1');
INSERT INTO itinelib.vehicule (IDCATEGORIEVEHICULE) VALUE ('1');
INSERT INTO itinelib.vehicule (IDCATEGORIEVEHICULE) VALUE ('1');
INSERT INTO itinelib.vehicule (IDCATEGORIEVEHICULE) VALUE ('1');
INSERT INTO itinelib.vehicule (IDCATEGORIEVEHICULE) VALUE ('1');
INSERT INTO itinelib.vehicule (IDCATEGORIEVEHICULE) VALUE ('1');
INSERT INTO itinelib.vehicule (IDCATEGORIEVEHICULE) VALUE ('1');
INSERT INTO itinelib.vehicule (IDCATEGORIEVEHICULE) VALUE ('1');
INSERT INTO itinelib.vehicule (IDCATEGORIEVEHICULE) VALUE ('1');
INSERT INTO itinelib.vehicule (IDCATEGORIEVEHICULE) VALUE ('1');
INSERT INTO itinelib.vehicule (IDCATEGORIEVEHICULE) VALUE ('1');
INSERT INTO itinelib.vehicule (IDCATEGORIEVEHICULE) VALUE ('1');
INSERT INTO itinelib.vehicule (IDCATEGORIEVEHICULE) VALUE ('1');
INSERT INTO itinelib.vehicule (IDCATEGORIEVEHICULE) VALUE ('1');
INSERT INTO itinelib.vehicule (IDCATEGORIEVEHICULE) VALUE ('1');
INSERT INTO itinelib.vehicule (IDCATEGORIEVEHICULE) VALUE ('1');
INSERT INTO itinelib.vehicule (IDCATEGORIEVEHICULE) VALUE ('1');
INSERT INTO itinelib.vehicule (IDCATEGORIEVEHICULE) VALUE ('1');
INSERT INTO itinelib.vehicule (IDCATEGORIEVEHICULE) VALUE ('1');
INSERT INTO itinelib.vehicule (IDCATEGORIEVEHICULE) VALUE ('1');
INSERT INTO itinelib.vehicule (IDCATEGORIEVEHICULE) VALUE ('1');
INSERT INTO itinelib.vehicule (IDCATEGORIEVEHICULE) VALUE ('1');
INSERT INTO itinelib.vehicule (IDCATEGORIEVEHICULE) VALUE ('1');
INSERT INTO itinelib.vehicule (IDCATEGORIEVEHICULE) VALUE ('1');
INSERT INTO itinelib.vehicule (IDCATEGORIEVEHICULE) VALUE ('1');
INSERT INTO itinelib.vehicule (IDCATEGORIEVEHICULE) VALUE ('2');
INSERT INTO itinelib.vehicule (IDCATEGORIEVEHICULE) VALUE ('2');
INSERT INTO itinelib.vehicule (IDCATEGORIEVEHICULE) VALUE ('2');
INSERT INTO itinelib.vehicule (IDCATEGORIEVEHICULE) VALUE ('2');
INSERT INTO itinelib.vehicule (IDCATEGORIEVEHICULE) VALUE ('2');
INSERT INTO itinelib.vehicule (IDCATEGORIEVEHICULE) VALUE ('2');
INSERT INTO itinelib.vehicule (IDCATEGORIEVEHICULE) VALUE ('2');
INSERT INTO itinelib.vehicule (IDCATEGORIEVEHICULE) VALUE ('2');
INSERT INTO itinelib.vehicule (IDCATEGORIEVEHICULE) VALUE ('2');
INSERT INTO itinelib.vehicule (IDCATEGORIEVEHICULE) VALUE ('2');
INSERT INTO itinelib.vehicule (IDCATEGORIEVEHICULE) VALUE ('2');
INSERT INTO itinelib.vehicule (IDCATEGORIEVEHICULE) VALUE ('2');
INSERT INTO itinelib.vehicule (IDCATEGORIEVEHICULE) VALUE ('2');
INSERT INTO itinelib.vehicule (IDCATEGORIEVEHICULE) VALUE ('2');
INSERT INTO itinelib.vehicule (IDCATEGORIEVEHICULE) VALUE ('2');
INSERT INTO itinelib.vehicule (IDCATEGORIEVEHICULE) VALUE ('2');
INSERT INTO itinelib.vehicule (IDCATEGORIEVEHICULE) VALUE ('2');
INSERT INTO itinelib.vehicule (IDCATEGORIEVEHICULE) VALUE ('2');
INSERT INTO itinelib.vehicule (IDCATEGORIEVEHICULE) VALUE ('2');
INSERT INTO itinelib.vehicule (IDCATEGORIEVEHICULE) VALUE ('2');
INSERT INTO itinelib.vehicule (IDCATEGORIEVEHICULE) VALUE ('2');
INSERT INTO itinelib.vehicule (IDCATEGORIEVEHICULE) VALUE ('2');
INSERT INTO itinelib.vehicule (IDCATEGORIEVEHICULE) VALUE ('2');
INSERT INTO itinelib.vehicule (IDCATEGORIEVEHICULE) VALUE ('2');
INSERT INTO itinelib.vehicule (IDCATEGORIEVEHICULE) VALUE ('2');
INSERT INTO itinelib.vehicule (IDCATEGORIEVEHICULE) VALUE ('2');
INSERT INTO itinelib.vehicule (IDCATEGORIEVEHICULE) VALUE ('2');
INSERT INTO itinelib.vehicule (IDCATEGORIEVEHICULE) VALUE ('2');
INSERT INTO itinelib.vehicule (IDCATEGORIEVEHICULE) VALUE ('2');
INSERT INTO itinelib.vehicule (IDCATEGORIEVEHICULE) VALUE ('2');
INSERT INTO itinelib.vehicule (IDCATEGORIEVEHICULE) VALUE ('2');
INSERT INTO itinelib.vehicule (IDCATEGORIEVEHICULE) VALUE ('2');
INSERT INTO itinelib.vehicule (IDCATEGORIEVEHICULE) VALUE ('2');
INSERT INTO itinelib.vehicule (IDCATEGORIEVEHICULE) VALUE ('2');
INSERT INTO itinelib.vehicule (IDCATEGORIEVEHICULE) VALUE ('2');
INSERT INTO itinelib.vehicule (IDCATEGORIEVEHICULE) VALUE ('2');
INSERT INTO itinelib.vehicule (IDCATEGORIEVEHICULE) VALUE ('2');
INSERT INTO itinelib.vehicule (IDCATEGORIEVEHICULE) VALUE ('2');
INSERT INTO itinelib.vehicule (IDCATEGORIEVEHICULE) VALUE ('2');
INSERT INTO itinelib.vehicule (IDCATEGORIEVEHICULE) VALUE ('2');

/*****************************************************************************
*EMPLACEMENT
******************************************************************************/

INSERT INTO itinelib.emplacement (IDCATEGORIEVEHICULE, IDPOINTLOCATION) VALUE ('2','19');
INSERT INTO itinelib.emplacement (IDCATEGORIEVEHICULE, IDPOINTLOCATION) VALUE ('2','19');
INSERT INTO itinelib.emplacement (IDCATEGORIEVEHICULE, IDPOINTLOCATION) VALUE ('2','14');
INSERT INTO itinelib.emplacement (IDCATEGORIEVEHICULE, IDPOINTLOCATION) VALUE ('2','6');
INSERT INTO itinelib.emplacement (IDCATEGORIEVEHICULE, IDPOINTLOCATION) VALUE ('2','18');
INSERT INTO itinelib.emplacement (IDCATEGORIEVEHICULE, IDPOINTLOCATION) VALUE ('1','8');
INSERT INTO itinelib.emplacement (IDCATEGORIEVEHICULE, IDPOINTLOCATION) VALUE ('1','18');
INSERT INTO itinelib.emplacement (IDCATEGORIEVEHICULE, IDPOINTLOCATION) VALUE ('1','7');
INSERT INTO itinelib.emplacement (IDCATEGORIEVEHICULE, IDPOINTLOCATION) VALUE ('1','20');
INSERT INTO itinelib.emplacement (IDCATEGORIEVEHICULE, IDPOINTLOCATION) VALUE ('2','3');
INSERT INTO itinelib.emplacement (IDCATEGORIEVEHICULE, IDPOINTLOCATION) VALUE ('2','13');
INSERT INTO itinelib.emplacement (IDCATEGORIEVEHICULE, IDPOINTLOCATION) VALUE ('2','7');
INSERT INTO itinelib.emplacement (IDCATEGORIEVEHICULE, IDPOINTLOCATION) VALUE ('1','8');
INSERT INTO itinelib.emplacement (IDCATEGORIEVEHICULE, IDPOINTLOCATION) VALUE ('1','17');
INSERT INTO itinelib.emplacement (IDCATEGORIEVEHICULE, IDPOINTLOCATION) VALUE ('2','17');
INSERT INTO itinelib.emplacement (IDCATEGORIEVEHICULE, IDPOINTLOCATION) VALUE ('2','14');
INSERT INTO itinelib.emplacement (IDCATEGORIEVEHICULE, IDPOINTLOCATION) VALUE ('2','10');
INSERT INTO itinelib.emplacement (IDCATEGORIEVEHICULE, IDPOINTLOCATION) VALUE ('2','15');
INSERT INTO itinelib.emplacement (IDCATEGORIEVEHICULE, IDPOINTLOCATION) VALUE ('1','13');
INSERT INTO itinelib.emplacement (IDCATEGORIEVEHICULE, IDPOINTLOCATION) VALUE ('1','1');
INSERT INTO itinelib.emplacement (IDCATEGORIEVEHICULE, IDPOINTLOCATION) VALUE ('1','5');
INSERT INTO itinelib.emplacement (IDCATEGORIEVEHICULE, IDPOINTLOCATION) VALUE ('1','14');
INSERT INTO itinelib.emplacement (IDCATEGORIEVEHICULE, IDPOINTLOCATION) VALUE ('1','12');
INSERT INTO itinelib.emplacement (IDCATEGORIEVEHICULE, IDPOINTLOCATION) VALUE ('1','5');
INSERT INTO itinelib.emplacement (IDCATEGORIEVEHICULE, IDPOINTLOCATION) VALUE ('2','19');
INSERT INTO itinelib.emplacement (IDCATEGORIEVEHICULE, IDPOINTLOCATION) VALUE ('1','5');
INSERT INTO itinelib.emplacement (IDCATEGORIEVEHICULE, IDPOINTLOCATION) VALUE ('2','3');
INSERT INTO itinelib.emplacement (IDCATEGORIEVEHICULE, IDPOINTLOCATION) VALUE ('2','19');
INSERT INTO itinelib.emplacement (IDCATEGORIEVEHICULE, IDPOINTLOCATION) VALUE ('1','16');
INSERT INTO itinelib.emplacement (IDCATEGORIEVEHICULE, IDPOINTLOCATION) VALUE ('2','9');
INSERT INTO itinelib.emplacement (IDCATEGORIEVEHICULE, IDPOINTLOCATION) VALUE ('2','10');
INSERT INTO itinelib.emplacement (IDCATEGORIEVEHICULE, IDPOINTLOCATION) VALUE ('1','7');
INSERT INTO itinelib.emplacement (IDCATEGORIEVEHICULE, IDPOINTLOCATION) VALUE ('2','15');
INSERT INTO itinelib.emplacement (IDCATEGORIEVEHICULE, IDPOINTLOCATION) VALUE ('1','3');
INSERT INTO itinelib.emplacement (IDCATEGORIEVEHICULE, IDPOINTLOCATION) VALUE ('1','1');
INSERT INTO itinelib.emplacement (IDCATEGORIEVEHICULE, IDPOINTLOCATION) VALUE ('1','17');
INSERT INTO itinelib.emplacement (IDCATEGORIEVEHICULE, IDPOINTLOCATION) VALUE ('1','11');
INSERT INTO itinelib.emplacement (IDCATEGORIEVEHICULE, IDPOINTLOCATION) VALUE ('1','8');
INSERT INTO itinelib.emplacement (IDCATEGORIEVEHICULE, IDPOINTLOCATION) VALUE ('1','11');
INSERT INTO itinelib.emplacement (IDCATEGORIEVEHICULE, IDPOINTLOCATION) VALUE ('2','13');
INSERT INTO itinelib.emplacement (IDCATEGORIEVEHICULE, IDPOINTLOCATION) VALUE ('1','18');
INSERT INTO itinelib.emplacement (IDCATEGORIEVEHICULE, IDPOINTLOCATION) VALUE ('2','19');
INSERT INTO itinelib.emplacement (IDCATEGORIEVEHICULE, IDPOINTLOCATION) VALUE ('1','8');
INSERT INTO itinelib.emplacement (IDCATEGORIEVEHICULE, IDPOINTLOCATION) VALUE ('2','11');
INSERT INTO itinelib.emplacement (IDCATEGORIEVEHICULE, IDPOINTLOCATION) VALUE ('1','11');
INSERT INTO itinelib.emplacement (IDCATEGORIEVEHICULE, IDPOINTLOCATION) VALUE ('2','15');
INSERT INTO itinelib.emplacement (IDCATEGORIEVEHICULE, IDPOINTLOCATION) VALUE ('1','2');
INSERT INTO itinelib.emplacement (IDCATEGORIEVEHICULE, IDPOINTLOCATION) VALUE ('1','20');
INSERT INTO itinelib.emplacement (IDCATEGORIEVEHICULE, IDPOINTLOCATION) VALUE ('2','2');
INSERT INTO itinelib.emplacement (IDCATEGORIEVEHICULE, IDPOINTLOCATION) VALUE ('1','2');
INSERT INTO itinelib.emplacement (IDCATEGORIEVEHICULE, IDPOINTLOCATION) VALUE ('1','5');
INSERT INTO itinelib.emplacement (IDCATEGORIEVEHICULE, IDPOINTLOCATION) VALUE ('2','8');
INSERT INTO itinelib.emplacement (IDCATEGORIEVEHICULE, IDPOINTLOCATION) VALUE ('2','8');
INSERT INTO itinelib.emplacement (IDCATEGORIEVEHICULE, IDPOINTLOCATION) VALUE ('2','17');
INSERT INTO itinelib.emplacement (IDCATEGORIEVEHICULE, IDPOINTLOCATION) VALUE ('2','7');
INSERT INTO itinelib.emplacement (IDCATEGORIEVEHICULE, IDPOINTLOCATION) VALUE ('1','7');
INSERT INTO itinelib.emplacement (IDCATEGORIEVEHICULE, IDPOINTLOCATION) VALUE ('1','6');
INSERT INTO itinelib.emplacement (IDCATEGORIEVEHICULE, IDPOINTLOCATION) VALUE ('1','6');
INSERT INTO itinelib.emplacement (IDCATEGORIEVEHICULE, IDPOINTLOCATION) VALUE ('2','3');
INSERT INTO itinelib.emplacement (IDCATEGORIEVEHICULE, IDPOINTLOCATION) VALUE ('2','17');
INSERT INTO itinelib.emplacement (IDCATEGORIEVEHICULE, IDPOINTLOCATION) VALUE ('2','15');
INSERT INTO itinelib.emplacement (IDCATEGORIEVEHICULE, IDPOINTLOCATION) VALUE ('2','14');
INSERT INTO itinelib.emplacement (IDCATEGORIEVEHICULE, IDPOINTLOCATION) VALUE ('2','12');
INSERT INTO itinelib.emplacement (IDCATEGORIEVEHICULE, IDPOINTLOCATION) VALUE ('2','12');
INSERT INTO itinelib.emplacement (IDCATEGORIEVEHICULE, IDPOINTLOCATION) VALUE ('2','16');
INSERT INTO itinelib.emplacement (IDCATEGORIEVEHICULE, IDPOINTLOCATION) VALUE ('2','15');
INSERT INTO itinelib.emplacement (IDCATEGORIEVEHICULE, IDPOINTLOCATION) VALUE ('2','11');
INSERT INTO itinelib.emplacement (IDCATEGORIEVEHICULE, IDPOINTLOCATION) VALUE ('1','15');
INSERT INTO itinelib.emplacement (IDCATEGORIEVEHICULE, IDPOINTLOCATION) VALUE ('2','18');
INSERT INTO itinelib.emplacement (IDCATEGORIEVEHICULE, IDPOINTLOCATION) VALUE ('2','17');
INSERT INTO itinelib.emplacement (IDCATEGORIEVEHICULE, IDPOINTLOCATION) VALUE ('1','1');
INSERT INTO itinelib.emplacement (IDCATEGORIEVEHICULE, IDPOINTLOCATION) VALUE ('1','9');
INSERT INTO itinelib.emplacement (IDCATEGORIEVEHICULE, IDPOINTLOCATION) VALUE ('1','9');
INSERT INTO itinelib.emplacement (IDCATEGORIEVEHICULE, IDPOINTLOCATION) VALUE ('2','20');
INSERT INTO itinelib.emplacement (IDCATEGORIEVEHICULE, IDPOINTLOCATION) VALUE ('2','10');
INSERT INTO itinelib.emplacement (IDCATEGORIEVEHICULE, IDPOINTLOCATION) VALUE ('2','4');
INSERT INTO itinelib.emplacement (IDCATEGORIEVEHICULE, IDPOINTLOCATION) VALUE ('1','8');
INSERT INTO itinelib.emplacement (IDCATEGORIEVEHICULE, IDPOINTLOCATION) VALUE ('2','20');
INSERT INTO itinelib.emplacement (IDCATEGORIEVEHICULE, IDPOINTLOCATION) VALUE ('2','11');
INSERT INTO itinelib.emplacement (IDCATEGORIEVEHICULE, IDPOINTLOCATION) VALUE ('2','12');
INSERT INTO itinelib.emplacement (IDCATEGORIEVEHICULE, IDPOINTLOCATION) VALUE ('1','4');
INSERT INTO itinelib.emplacement (IDCATEGORIEVEHICULE, IDPOINTLOCATION) VALUE ('1','6');
INSERT INTO itinelib.emplacement (IDCATEGORIEVEHICULE, IDPOINTLOCATION) VALUE ('2','10');
INSERT INTO itinelib.emplacement (IDCATEGORIEVEHICULE, IDPOINTLOCATION) VALUE ('1','14');
INSERT INTO itinelib.emplacement (IDCATEGORIEVEHICULE, IDPOINTLOCATION) VALUE ('1','12');
INSERT INTO itinelib.emplacement (IDCATEGORIEVEHICULE, IDPOINTLOCATION) VALUE ('2','12');
INSERT INTO itinelib.emplacement (IDCATEGORIEVEHICULE, IDPOINTLOCATION) VALUE ('2','14');
INSERT INTO itinelib.emplacement (IDCATEGORIEVEHICULE, IDPOINTLOCATION) VALUE ('1','18');
INSERT INTO itinelib.emplacement (IDCATEGORIEVEHICULE, IDPOINTLOCATION) VALUE ('1','15');
INSERT INTO itinelib.emplacement (IDCATEGORIEVEHICULE, IDPOINTLOCATION) VALUE ('2','14');
INSERT INTO itinelib.emplacement (IDCATEGORIEVEHICULE, IDPOINTLOCATION) VALUE ('1','14');
INSERT INTO itinelib.emplacement (IDCATEGORIEVEHICULE, IDPOINTLOCATION) VALUE ('2','8');
INSERT INTO itinelib.emplacement (IDCATEGORIEVEHICULE, IDPOINTLOCATION) VALUE ('1','15');
INSERT INTO itinelib.emplacement (IDCATEGORIEVEHICULE, IDPOINTLOCATION) VALUE ('1','20');
INSERT INTO itinelib.emplacement (IDCATEGORIEVEHICULE, IDPOINTLOCATION) VALUE ('1','19');
INSERT INTO itinelib.emplacement (IDCATEGORIEVEHICULE, IDPOINTLOCATION) VALUE ('2','12');
INSERT INTO itinelib.emplacement (IDCATEGORIEVEHICULE, IDPOINTLOCATION) VALUE ('1','18');
INSERT INTO itinelib.emplacement (IDCATEGORIEVEHICULE, IDPOINTLOCATION) VALUE ('2','17');
INSERT INTO itinelib.emplacement (IDCATEGORIEVEHICULE, IDPOINTLOCATION) VALUE ('1','17');
INSERT INTO itinelib.emplacement (IDCATEGORIEVEHICULE, IDPOINTLOCATION) VALUE ('2','14');
INSERT INTO itinelib.emplacement (IDCATEGORIEVEHICULE, IDPOINTLOCATION) VALUE ('1','1');
INSERT INTO itinelib.emplacement (IDCATEGORIEVEHICULE, IDPOINTLOCATION) VALUE ('1','20');
INSERT INTO itinelib.emplacement (IDCATEGORIEVEHICULE, IDPOINTLOCATION) VALUE ('2','6');
INSERT INTO itinelib.emplacement (IDCATEGORIEVEHICULE, IDPOINTLOCATION) VALUE ('2','18');
INSERT INTO itinelib.emplacement (IDCATEGORIEVEHICULE, IDPOINTLOCATION) VALUE ('2','15');
INSERT INTO itinelib.emplacement (IDCATEGORIEVEHICULE, IDPOINTLOCATION) VALUE ('2','4');
INSERT INTO itinelib.emplacement (IDCATEGORIEVEHICULE, IDPOINTLOCATION) VALUE ('1','8');
INSERT INTO itinelib.emplacement (IDCATEGORIEVEHICULE, IDPOINTLOCATION) VALUE ('2','9');
INSERT INTO itinelib.emplacement (IDCATEGORIEVEHICULE, IDPOINTLOCATION) VALUE ('1','19');
INSERT INTO itinelib.emplacement (IDCATEGORIEVEHICULE, IDPOINTLOCATION) VALUE ('1','8');
INSERT INTO itinelib.emplacement (IDCATEGORIEVEHICULE, IDPOINTLOCATION) VALUE ('2','20');
INSERT INTO itinelib.emplacement (IDCATEGORIEVEHICULE, IDPOINTLOCATION) VALUE ('2','19');
INSERT INTO itinelib.emplacement (IDCATEGORIEVEHICULE, IDPOINTLOCATION) VALUE ('2','16');
INSERT INTO itinelib.emplacement (IDCATEGORIEVEHICULE, IDPOINTLOCATION) VALUE ('2','4');
INSERT INTO itinelib.emplacement (IDCATEGORIEVEHICULE, IDPOINTLOCATION) VALUE ('2','7');
INSERT INTO itinelib.emplacement (IDCATEGORIEVEHICULE, IDPOINTLOCATION) VALUE ('2','1');
INSERT INTO itinelib.emplacement (IDCATEGORIEVEHICULE, IDPOINTLOCATION) VALUE ('1','3');
INSERT INTO itinelib.emplacement (IDCATEGORIEVEHICULE, IDPOINTLOCATION) VALUE ('2','3');
INSERT INTO itinelib.emplacement (IDCATEGORIEVEHICULE, IDPOINTLOCATION) VALUE ('1','18');
INSERT INTO itinelib.emplacement (IDCATEGORIEVEHICULE, IDPOINTLOCATION) VALUE ('2','9');
INSERT INTO itinelib.emplacement (IDCATEGORIEVEHICULE, IDPOINTLOCATION) VALUE ('2','11');
INSERT INTO itinelib.emplacement (IDCATEGORIEVEHICULE, IDPOINTLOCATION) VALUE ('2','20');
INSERT INTO itinelib.emplacement (IDCATEGORIEVEHICULE, IDPOINTLOCATION) VALUE ('2','3');
INSERT INTO itinelib.emplacement (IDCATEGORIEVEHICULE, IDPOINTLOCATION) VALUE ('1','1');
INSERT INTO itinelib.emplacement (IDCATEGORIEVEHICULE, IDPOINTLOCATION) VALUE ('1','18');
INSERT INTO itinelib.emplacement (IDCATEGORIEVEHICULE, IDPOINTLOCATION) VALUE ('1','18');
INSERT INTO itinelib.emplacement (IDCATEGORIEVEHICULE, IDPOINTLOCATION) VALUE ('2','8');
INSERT INTO itinelib.emplacement (IDCATEGORIEVEHICULE, IDPOINTLOCATION) VALUE ('2','14');
INSERT INTO itinelib.emplacement (IDCATEGORIEVEHICULE, IDPOINTLOCATION) VALUE ('1','13');
INSERT INTO itinelib.emplacement (IDCATEGORIEVEHICULE, IDPOINTLOCATION) VALUE ('2','16');
INSERT INTO itinelib.emplacement (IDCATEGORIEVEHICULE, IDPOINTLOCATION) VALUE ('2','15');
INSERT INTO itinelib.emplacement (IDCATEGORIEVEHICULE, IDPOINTLOCATION) VALUE ('2','7');
INSERT INTO itinelib.emplacement (IDCATEGORIEVEHICULE, IDPOINTLOCATION) VALUE ('2','16');
INSERT INTO itinelib.emplacement (IDCATEGORIEVEHICULE, IDPOINTLOCATION) VALUE ('1','6');
INSERT INTO itinelib.emplacement (IDCATEGORIEVEHICULE, IDPOINTLOCATION) VALUE ('2','9');
INSERT INTO itinelib.emplacement (IDCATEGORIEVEHICULE, IDPOINTLOCATION) VALUE ('2','5');
INSERT INTO itinelib.emplacement (IDCATEGORIEVEHICULE, IDPOINTLOCATION) VALUE ('2','5');
INSERT INTO itinelib.emplacement (IDCATEGORIEVEHICULE, IDPOINTLOCATION) VALUE ('1','18');
INSERT INTO itinelib.emplacement (IDCATEGORIEVEHICULE, IDPOINTLOCATION) VALUE ('1','14');
INSERT INTO itinelib.emplacement (IDCATEGORIEVEHICULE, IDPOINTLOCATION) VALUE ('2','9');
INSERT INTO itinelib.emplacement (IDCATEGORIEVEHICULE, IDPOINTLOCATION) VALUE ('2','7');
INSERT INTO itinelib.emplacement (IDCATEGORIEVEHICULE, IDPOINTLOCATION) VALUE ('1','8');
INSERT INTO itinelib.emplacement (IDCATEGORIEVEHICULE, IDPOINTLOCATION) VALUE ('2','4');
INSERT INTO itinelib.emplacement (IDCATEGORIEVEHICULE, IDPOINTLOCATION) VALUE ('1','18');
INSERT INTO itinelib.emplacement (IDCATEGORIEVEHICULE, IDPOINTLOCATION) VALUE ('2','20');
INSERT INTO itinelib.emplacement (IDCATEGORIEVEHICULE, IDPOINTLOCATION) VALUE ('2','16');
INSERT INTO itinelib.emplacement (IDCATEGORIEVEHICULE, IDPOINTLOCATION) VALUE ('2','10');
INSERT INTO itinelib.emplacement (IDCATEGORIEVEHICULE, IDPOINTLOCATION) VALUE ('1','11');
INSERT INTO itinelib.emplacement (IDCATEGORIEVEHICULE, IDPOINTLOCATION) VALUE ('1','12');
INSERT INTO itinelib.emplacement (IDCATEGORIEVEHICULE, IDPOINTLOCATION) VALUE ('2','19');
INSERT INTO itinelib.emplacement (IDCATEGORIEVEHICULE, IDPOINTLOCATION) VALUE ('1','10');
INSERT INTO itinelib.emplacement (IDCATEGORIEVEHICULE, IDPOINTLOCATION) VALUE ('1','20');
INSERT INTO itinelib.emplacement (IDCATEGORIEVEHICULE, IDPOINTLOCATION) VALUE ('2','8');
INSERT INTO itinelib.emplacement (IDCATEGORIEVEHICULE, IDPOINTLOCATION) VALUE ('2','2');
INSERT INTO itinelib.emplacement (IDCATEGORIEVEHICULE, IDPOINTLOCATION) VALUE ('1','15');
INSERT INTO itinelib.emplacement (IDCATEGORIEVEHICULE, IDPOINTLOCATION) VALUE ('2','13');
INSERT INTO itinelib.emplacement (IDCATEGORIEVEHICULE, IDPOINTLOCATION) VALUE ('1','18');
INSERT INTO itinelib.emplacement (IDCATEGORIEVEHICULE, IDPOINTLOCATION) VALUE ('2','17');
INSERT INTO itinelib.emplacement (IDCATEGORIEVEHICULE, IDPOINTLOCATION) VALUE ('1','2');
INSERT INTO itinelib.emplacement (IDCATEGORIEVEHICULE, IDPOINTLOCATION) VALUE ('2','18');
INSERT INTO itinelib.emplacement (IDCATEGORIEVEHICULE, IDPOINTLOCATION) VALUE ('1','7');
INSERT INTO itinelib.emplacement (IDCATEGORIEVEHICULE, IDPOINTLOCATION) VALUE ('2','15');
INSERT INTO itinelib.emplacement (IDCATEGORIEVEHICULE, IDPOINTLOCATION) VALUE ('2','16');
INSERT INTO itinelib.emplacement (IDCATEGORIEVEHICULE, IDPOINTLOCATION) VALUE ('1','1');
INSERT INTO itinelib.emplacement (IDCATEGORIEVEHICULE, IDPOINTLOCATION) VALUE ('1','2');
INSERT INTO itinelib.emplacement (IDCATEGORIEVEHICULE, IDPOINTLOCATION) VALUE ('2','8');
INSERT INTO itinelib.emplacement (IDCATEGORIEVEHICULE, IDPOINTLOCATION) VALUE ('2','2');
INSERT INTO itinelib.emplacement (IDCATEGORIEVEHICULE, IDPOINTLOCATION) VALUE ('1','6');
INSERT INTO itinelib.emplacement (IDCATEGORIEVEHICULE, IDPOINTLOCATION) VALUE ('1','4');
INSERT INTO itinelib.emplacement (IDCATEGORIEVEHICULE, IDPOINTLOCATION) VALUE ('1','11');
INSERT INTO itinelib.emplacement (IDCATEGORIEVEHICULE, IDPOINTLOCATION) VALUE ('2','18');
INSERT INTO itinelib.emplacement (IDCATEGORIEVEHICULE, IDPOINTLOCATION) VALUE ('1','1');
INSERT INTO itinelib.emplacement (IDCATEGORIEVEHICULE, IDPOINTLOCATION) VALUE ('2','2');
INSERT INTO itinelib.emplacement (IDCATEGORIEVEHICULE, IDPOINTLOCATION) VALUE ('2','16');
INSERT INTO itinelib.emplacement (IDCATEGORIEVEHICULE, IDPOINTLOCATION) VALUE ('1','11');
INSERT INTO itinelib.emplacement (IDCATEGORIEVEHICULE, IDPOINTLOCATION) VALUE ('2','5');
INSERT INTO itinelib.emplacement (IDCATEGORIEVEHICULE, IDPOINTLOCATION) VALUE ('2','6');
INSERT INTO itinelib.emplacement (IDCATEGORIEVEHICULE, IDPOINTLOCATION) VALUE ('2','13');
INSERT INTO itinelib.emplacement (IDCATEGORIEVEHICULE, IDPOINTLOCATION) VALUE ('1','4');
INSERT INTO itinelib.emplacement (IDCATEGORIEVEHICULE, IDPOINTLOCATION) VALUE ('2','9');
INSERT INTO itinelib.emplacement (IDCATEGORIEVEHICULE, IDPOINTLOCATION) VALUE ('1','13');
INSERT INTO itinelib.emplacement (IDCATEGORIEVEHICULE, IDPOINTLOCATION) VALUE ('2','16');
INSERT INTO itinelib.emplacement (IDCATEGORIEVEHICULE, IDPOINTLOCATION) VALUE ('2','3');
INSERT INTO itinelib.emplacement (IDCATEGORIEVEHICULE, IDPOINTLOCATION) VALUE ('1','4');
INSERT INTO itinelib.emplacement (IDCATEGORIEVEHICULE, IDPOINTLOCATION) VALUE ('1','9');
INSERT INTO itinelib.emplacement (IDCATEGORIEVEHICULE, IDPOINTLOCATION) VALUE ('2','5');
INSERT INTO itinelib.emplacement (IDCATEGORIEVEHICULE, IDPOINTLOCATION) VALUE ('1','16');
INSERT INTO itinelib.emplacement (IDCATEGORIEVEHICULE, IDPOINTLOCATION) VALUE ('1','2');
INSERT INTO itinelib.emplacement (IDCATEGORIEVEHICULE, IDPOINTLOCATION) VALUE ('2','2');
INSERT INTO itinelib.emplacement (IDCATEGORIEVEHICULE, IDPOINTLOCATION) VALUE ('2','1');
INSERT INTO itinelib.emplacement (IDCATEGORIEVEHICULE, IDPOINTLOCATION) VALUE ('2','10');
INSERT INTO itinelib.emplacement (IDCATEGORIEVEHICULE, IDPOINTLOCATION) VALUE ('1','9');
INSERT INTO itinelib.emplacement (IDCATEGORIEVEHICULE, IDPOINTLOCATION) VALUE ('2','3');
INSERT INTO itinelib.emplacement (IDCATEGORIEVEHICULE, IDPOINTLOCATION) VALUE ('1','17');
INSERT INTO itinelib.emplacement (IDCATEGORIEVEHICULE, IDPOINTLOCATION) VALUE ('1','15');
INSERT INTO itinelib.emplacement (IDCATEGORIEVEHICULE, IDPOINTLOCATION) VALUE ('1','12');
INSERT INTO itinelib.emplacement (IDCATEGORIEVEHICULE, IDPOINTLOCATION) VALUE ('1','1');
INSERT INTO itinelib.emplacement (IDCATEGORIEVEHICULE, IDPOINTLOCATION) VALUE ('1','1');
INSERT INTO itinelib.emplacement (IDCATEGORIEVEHICULE, IDPOINTLOCATION) VALUE ('1','9');
INSERT INTO itinelib.emplacement (IDCATEGORIEVEHICULE, IDPOINTLOCATION) VALUE ('1','10');

/*********************************************************************************************************
*INCLURE
***********************************************************************************************************/

INSERT INTO itinelib.inclure (IDCATEGORIEVEHICULE, IDTYPE) VALUE ('1','1');
INSERT INTO itinelib.inclure (IDCATEGORIEVEHICULE, IDTYPE) VALUE ('1','3');
INSERT INTO itinelib.inclure (IDCATEGORIEVEHICULE, IDTYPE) VALUE ('2','2');
INSERT INTO itinelib.inclure (IDCATEGORIEVEHICULE, IDTYPE) VALUE ('2','3');


/*************************************************************************************************************
*RESAGLOBALE
***************************************************************************************************************/

INSERT INTO itinelib.resaglobale (IDABONNEMENT, DHCREATION, DHANNULATION) VALUE (1, '2012-04-23 16:00', NULL);
INSERT INTO itinelib.resaglobale (IDABONNEMENT, DHCREATION, DHANNULATION) VALUE (2, '2012-04-23 16:30', NULL);
INSERT INTO itinelib.resaglobale (IDABONNEMENT, DHCREATION, DHANNULATION) VALUE (3, '2012-04-23 18:15', NULL);
INSERT INTO itinelib.resaglobale (IDABONNEMENT, DHCREATION, DHANNULATION) VALUE (1, '2012-04-23 21:35', NULL);

/*****************************************************************************************************************
*REGISTRE
*******************************************************************************************************************/


INSERT INTO itinelib.registre (IDPOINTLOCATION, POI_IDPOINTLOCATION, IDVEHICULE, IDABONNEMENT, IDRESAGLOBALE, IDEMPLACEMENT, IDEMPLOYE, DHDEBUTLOCATION, DHRETOURLOCATION, DHARRIVEECLIENT, DHRESERVATIONPREVUE, DHANNULATIONRESERVATION, DHDEBUTDEPLACEMENT, DHRETOURDEPLACEMENT) VALUE ('1','2',null,'1','1',null,null,null,null,null,'2012-04-24 16:00',null,null,null);
INSERT INTO itinelib.registre (IDPOINTLOCATION, POI_IDPOINTLOCATION, IDVEHICULE, IDABONNEMENT, IDRESAGLOBALE, IDEMPLACEMENT, IDEMPLOYE, DHDEBUTLOCATION, DHRETOURLOCATION, DHARRIVEECLIENT, DHRESERVATIONPREVUE, DHANNULATIONRESERVATION, DHDEBUTDEPLACEMENT, DHRETOURDEPLACEMENT) VALUE ('2','3',null,'1','1',null,null,null,null,null,'2012-04-24 16:00',null,null,null);
INSERT INTO itinelib.registre (IDPOINTLOCATION, POI_IDPOINTLOCATION, IDVEHICULE, IDABONNEMENT, IDRESAGLOBALE, IDEMPLACEMENT, IDEMPLOYE, DHDEBUTLOCATION, DHRETOURLOCATION, DHARRIVEECLIENT, DHRESERVATIONPREVUE, DHANNULATIONRESERVATION, DHDEBUTDEPLACEMENT, DHRETOURDEPLACEMENT) VALUE ('3','4',null,'1','1',null,null,null,null,null,'2012-04-24 16:00',null,null,null);
INSERT INTO itinelib.registre (IDPOINTLOCATION, POI_IDPOINTLOCATION, IDVEHICULE, IDABONNEMENT, IDRESAGLOBALE, IDEMPLACEMENT, IDEMPLOYE, DHDEBUTLOCATION, DHRETOURLOCATION, DHARRIVEECLIENT, DHRESERVATIONPREVUE, DHANNULATIONRESERVATION, DHDEBUTDEPLACEMENT, DHRETOURDEPLACEMENT) VALUE ('4','5',null,'2','2',null,null,null,null,null,'2012-04-24 16:00',null,null,null);
INSERT INTO itinelib.registre (IDPOINTLOCATION, POI_IDPOINTLOCATION, IDVEHICULE, IDABONNEMENT, IDRESAGLOBALE, IDEMPLACEMENT, IDEMPLOYE, DHDEBUTLOCATION, DHRETOURLOCATION, DHARRIVEECLIENT, DHRESERVATIONPREVUE, DHANNULATIONRESERVATION, DHDEBUTDEPLACEMENT, DHRETOURDEPLACEMENT) VALUE ('4','5','5','8',null,'21',null,'2012-05-06 15:00','2012-05-06 16:00',null,null,null,null,null);
INSERT INTO itinelib.registre (IDPOINTLOCATION, POI_IDPOINTLOCATION, IDVEHICULE, IDABONNEMENT, IDRESAGLOBALE, IDEMPLACEMENT, IDEMPLOYE, DHDEBUTLOCATION, DHRETOURLOCATION, DHARRIVEECLIENT, DHRESERVATIONPREVUE, DHANNULATIONRESERVATION, DHDEBUTDEPLACEMENT, DHRETOURDEPLACEMENT) VALUE ('5','6','1',null,null,'57','4',null,null,null,null,null,'2012-08-10 12:15','2012-08-10 12:45');

